import { mergeRuleFile, RULE_LIMITS, type RuleFormat } from "@logic2b/scaffold/rules"
import { CLI_PACKAGE_SELECTOR } from "@logic2b/scaffold/package-selectors"
import * as vscode from "vscode"

import {
  applyPresetToProject,
  agentRulesForProject,
  COMMAND_IDS,
  DEFAULT_REGISTRY,
  documentationUrl,
  normalizeRegistryUrl,
  registryKind,
  themePathFromCssEntry,
  type RegistryIndexItem,
} from "./core"
import { RegistryItemNode, RegistryTreeProvider } from "./registry-tree"

function registryUrl(): string {
  return normalizeRegistryUrl(
    vscode.workspace.getConfiguration("logic2b").get("registryUrl", DEFAULT_REGISTRY),
  )
}

async function pickWorkspaceFolder(): Promise<vscode.WorkspaceFolder | undefined> {
  const folders = vscode.workspace.workspaceFolders ?? []
  if (folders.length === 0) {
    await vscode.window.showErrorMessage("Open a workspace before using logic2b.")
    return undefined
  }
  if (folders.length === 1) return folders[0]
  return vscode.window.showWorkspaceFolderPick({
    placeHolder: "Choose the workspace where logic2b should make changes",
  })
}

async function fileExists(uri: vscode.Uri): Promise<boolean> {
  try {
    await vscode.workspace.fs.stat(uri)
    return true
  } catch {
    return false
  }
}

async function executeCliTask(
  folder: vscode.WorkspaceFolder,
  command: "init" | "add",
  args: string[],
): Promise<void> {
  const execution = new vscode.ShellExecution(
    "npx",
    [CLI_PACKAGE_SELECTOR, command, ...args, ...(vscode.workspace.getConfiguration("logic2b", folder.uri).get("agentRules", true) ? [] : ["--no-agent-rules"])],
    { cwd: folder.uri.fsPath },
  )
  const task = new vscode.Task(
    { type: "logic2b", command },
    folder,
    command === "init" ? "Initialize workspace" : `Install ${args.join(", ")}`,
    "logic2b",
    execution,
  )
  task.presentationOptions = {
    reveal: vscode.TaskRevealKind.Always,
    panel: vscode.TaskPanelKind.Dedicated,
    clear: true,
  }
  await vscode.tasks.executeTask(task)
}

async function initializeWorkspace(
  requestedFolder?: vscode.WorkspaceFolder,
): Promise<void> {
  const folder = requestedFolder ?? (await pickWorkspaceFolder())
  if (!folder) return
  const args = registryUrl() === DEFAULT_REGISTRY ? [] : ["--registry", registryUrl()]
  await executeCliTask(folder, "init", args)
}

async function ensureInitialized(
  folder: vscode.WorkspaceFolder,
): Promise<boolean> {
  const config = vscode.Uri.joinPath(folder.uri, "components.json")
  if (await fileExists(config)) return true
  const action = await vscode.window.showWarningMessage(
    "This workspace has no components.json. Initialize logic2b first, then run the install command again.",
    "Initialize",
  )
  if (action === "Initialize") await initializeWorkspace(folder)
  return false
}

async function installItems(
  provider: RegistryTreeProvider,
  requested?: RegistryIndexItem[],
): Promise<void> {
  let items = requested
  if (!items) {
    const installable = (await provider.getItems()).filter(
      (item) => registryKind(item) !== null,
    )
    const picks = await vscode.window.showQuickPick(
      installable.map((item) => ({
        label: item.title ?? item.name,
        description: item.name,
        detail: item.description,
        item,
      })),
      {
        canPickMany: true,
        matchOnDescription: true,
        matchOnDetail: true,
        placeHolder: "Choose components, blocks or charts to install",
        title: "Install from the logic2b registry",
      },
    )
    if (!picks || picks.length === 0) return
    items = picks.map((pick) => pick.item)
  }

  const folder = await pickWorkspaceFolder()
  if (!folder || !(await ensureInitialized(folder))) return
  await executeCliTask(
    folder,
    "add",
    [...new Set(items.map((item) => item.name))],
  )
}

function wholeDocumentRange(document: vscode.TextDocument): vscode.Range {
  return new vscode.Range(
    document.positionAt(0),
    document.positionAt(document.getText().length),
  )
}

async function applyPreset(): Promise<void> {
  const folder = await pickWorkspaceFolder()
  if (!folder) return
  const presetId = await vscode.window.showInputBox({
    title: "Apply a logic2b preset",
    prompt: "Paste the preset id generated by ui.logic2b.com/create",
    placeHolder: "Preset id",
    ignoreFocusOut: true,
  })
  if (!presetId) return

  const configUri = vscode.Uri.joinPath(folder.uri, "components.json")
  try {
    const configDocument = await vscode.workspace.openTextDocument(configUri)
    const configText = configDocument.getText()
    const configValue: unknown = JSON.parse(configText)
    if (
      typeof configValue !== "object" ||
      configValue === null ||
      Array.isArray(configValue)
    ) {
      throw new Error("components.json must be a JSON object.")
    }
    const cssEntry = (configValue as { tailwind?: { css?: unknown } }).tailwind?.css
    if (typeof cssEntry !== "string") {
      throw new Error('components.json must define "tailwind.css".')
    }

    // Resolve the theme path before opening it; applyPresetToProject validates
    // the same path again before any workspace edit is created.
    const pathSegments = themePathFromCssEntry(cssEntry).split("/")
    const themeUri = vscode.Uri.joinPath(
      folder.uri,
      ...pathSegments,
    )
    const themeDocument = await vscode.workspace.openTextDocument(themeUri)
    const patch = applyPresetToProject(configText, themeDocument.getText(), presetId)

    const edit = new vscode.WorkspaceEdit()
    edit.replace(configUri, wholeDocumentRange(configDocument), patch.config)
    edit.replace(themeUri, wholeDocumentRange(themeDocument), patch.themeCss)
    if (!(await vscode.workspace.applyEdit(edit))) {
      throw new Error("VS Code rejected the workspace edit.")
    }
    const saved = await Promise.all([configDocument.save(), themeDocument.save()])
    if (saved.some((value) => !value)) {
      throw new Error("The preset was applied in the editor but one file could not be saved.")
    }
    await vscode.window.showInformationMessage(
      `Applied preset: ${patch.preset.base} / ${patch.preset.theme} / ${patch.preset.radius}.`,
    )
  } catch (error) {
    await vscode.window.showErrorMessage(
      `Could not apply preset: ${error instanceof Error ? error.message : error}`,
    )
  }
}

async function rulesDocument(folder: vscode.WorkspaceFolder, path: string): Promise<vscode.TextDocument | undefined> {
  const parts = path.split("/")
  for (let i = 1; i <= parts.length; i++) {
    const uri = vscode.Uri.joinPath(folder.uri, ...parts.slice(0, i))
    try {
      const stat = await vscode.workspace.fs.stat(uri)
      if (stat.type & vscode.FileType.SymbolicLink) throw new Error(`Refusing symbolic link in ${path}.`)
      if (i === parts.length && (stat.type !== vscode.FileType.File || stat.size > RULE_LIMITS.documentBytes)) throw new Error(`${path} is not a bounded regular file.`)
    } catch (error) {
      if ((error as { code?: string }).code === "FileNotFound") return undefined
      throw error
    }
  }
  const document = await vscode.workspace.openTextDocument(vscode.Uri.joinPath(folder.uri, ...parts))
  if (new TextEncoder().encode(document.getText()).length > RULE_LIMITS.documentBytes) throw new Error(`${path} exceeds the document limit.`)
  return document
}

async function generateAgentRules(requestedFolder?: vscode.WorkspaceFolder, quiet = false): Promise<void> {
  const folder = requestedFolder ?? await pickWorkspaceFolder()
  if (!folder) return
  try {
    const config = await rulesDocument(folder, "components.json")
    if (!config) throw new Error("Initialize logic2b in this application first.")
    const manifest = await rulesDocument(folder, ".logic2b/manifest.json")
    const formats: RuleFormat[] = ["agents"]
    for (const [format, path] of [["claude", "CLAUDE.md"], ["cursor", ".cursor/rules/logic2b.mdc"], ["copilot", ".github/copilot-instructions.md"]] as const) {
      const doc = await rulesDocument(folder, path)
      if (doc && (format === "claude" ? /^@(?:\.\/)?AGENTS\.md\r?$/m.test(doc.getText()) : doc.getText().includes("<!-- logic2b:rules:"))) formats.push(format)
    }
    const plan = agentRulesForProject(config.getText(), manifest?.getText(), formats)
    const edit = new vscode.WorkspaceEdit()
    const changed: vscode.Uri[] = []
    for (const file of plan.files) {
      const document = await rulesDocument(folder, file.path)
      const result = mergeRuleFile(file, document?.getText())
      if (result.action === "unchanged") continue
      const uri = vscode.Uri.joinPath(folder.uri, ...file.path.split("/"))
      if (document) edit.replace(uri, wholeDocumentRange(document), result.content)
      else { edit.createFile(uri, { overwrite: false, ignoreIfExists: false }); edit.insert(uri, new vscode.Position(0, 0), result.content) }
      changed.push(uri)
    }
    if (changed.length) {
      if (!(await vscode.workspace.applyEdit(edit))) throw new Error("VS Code rejected the agent rules edit.")
      const saved = await Promise.all(changed.map(async uri => (await vscode.workspace.openTextDocument(uri)).save()))
      if (saved.some(value => !value)) throw new Error("Rules were edited, but one document could not be saved.")
    }
    if (!quiet) await vscode.window.showInformationMessage(`Agent rules: ${changed.length} document(s) updated.`)
  } catch (error) {
    await vscode.window.showErrorMessage(`Could not generate agent rules: ${error instanceof Error ? error.message : error}`)
  }
}

export function activate(context: vscode.ExtensionContext): void {
  const provider = new RegistryTreeProvider(registryUrl)
  context.subscriptions.push(
    provider,
    vscode.window.registerTreeDataProvider("logic2b.registry", provider),
    vscode.commands.registerCommand(COMMAND_IDS[0], () =>
      provider.refresh({ refetch: true }),
    ),
    vscode.commands.registerCommand(COMMAND_IDS[1], async () => {
      const query = await vscode.window.showInputBox({
        title: "Search the logic2b registry",
        placeHolder: "Component, block, chart or capability",
        value: provider.getQuery(),
      })
      if (query !== undefined) provider.setQuery(query)
    }),
    vscode.commands.registerCommand(
      COMMAND_IDS[2],
      async (node?: RegistryItemNode) => {
        if (node instanceof RegistryItemNode) await installItems(provider, [node.item])
        else await installItems(provider)
      },
    ),
    vscode.commands.registerCommand(COMMAND_IDS[3], () => installItems(provider)),
    vscode.commands.registerCommand(COMMAND_IDS[4], initializeWorkspace),
    vscode.commands.registerCommand(COMMAND_IDS[5], applyPreset),
    vscode.commands.registerCommand(COMMAND_IDS[8], () => generateAgentRules()),
    vscode.commands.registerCommand(COMMAND_IDS[6], () =>
      vscode.env.openExternal(vscode.Uri.parse(`${registryUrl()}/create`)),
    ),
    vscode.commands.registerCommand(
      COMMAND_IDS[7],
      async (node?: RegistryItemNode) => {
        if (!(node instanceof RegistryItemNode)) {
          await vscode.env.openExternal(vscode.Uri.parse(`${registryUrl()}/docs`))
          return
        }
        await vscode.env.openExternal(
          vscode.Uri.parse(documentationUrl(registryUrl(), node.item)),
        )
      },
    ),
  )

  const watcher = vscode.workspace.createFileSystemWatcher(
    "**/{components.json,.logic2b/manifest.json}",
  )
  watcher.onDidCreate(() => provider.refresh())
  watcher.onDidChange(() => provider.refresh())
  watcher.onDidDelete(() => provider.refresh())
  context.subscriptions.push(
    watcher,
    vscode.workspace.onDidChangeConfiguration((event) => {
      if (event.affectsConfiguration("logic2b.registryUrl")) {
        provider.refresh({ refetch: true })
      }
    }),
    vscode.tasks.onDidEndTaskProcess((event) => {
      if (event.execution.task.definition.type === "logic2b") {
        provider.refresh()
        const scope = event.execution.task.scope
        if (event.exitCode === 0 && scope && typeof scope === "object" && vscode.workspace.getConfiguration("logic2b", scope.uri).get("agentRules", true)) void generateAgentRules(scope, true)
      }
    }),
  )
}

export function deactivate(): void {}
