import { CLI_PACKAGE_SELECTOR, PACKAGE_RUNNERS, REGISTRY_DEFAULT_CHANNEL } from "@logic2b/scaffold/package-selectors"
import assert from "node:assert/strict"
import { execFile } from "node:child_process"
import { access, mkdtemp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises"
import { createServer } from "node:http"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"
import { promisify } from "node:util"

import { Client } from "@modelcontextprotocol/sdk/client/index.js"
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js"
import { McpError } from "@modelcontextprotocol/sdk/types.js"
import { DEFAULT_CONFIG, encodePreset } from "@logic2b/tokens"

const execFileAsync = promisify(execFile)
const repoRoot = resolve(import.meta.dirname, "../../..")
const cliRoot = join(repoRoot, "packages/cli")
const mcpRoot = join(repoRoot, "packages/mcp")
const registryRoot = join(repoRoot, "apps/web/public/r")
// Demo endpoints are generated by Astro, while registry payloads are public assets.
const builtRegistryRoot = join(repoRoot, "apps/web/dist/client/r")
const customerRegistryVersion = "1.0.0-rc.17"
const customerItems = ["admin-customers-01", "customer-edit-01"] as const

interface CustomerFixture {
  name: string
  files: Array<{ path: string; content: string }>
  behavior: { schemaVersion: 1; consumer: string[]; [key: string]: unknown }
  entry: { name: string; version: string; integrity: string; content: string }
}

async function json(path: string) {
  return JSON.parse(await readFile(path, "utf8")) as Record<string, unknown>
}

async function customerFixtures(version: string): Promise<Map<string, CustomerFixture>> {
  const manifest = await json(join(registryRoot, "versions", `${version}.json`)) as {
    version: string
    items: CustomerFixture["entry"][]
  }
  assert.equal(manifest.version, version)
  const fixtures = new Map<string, CustomerFixture>()
  for (const name of customerItems) {
    const entry = manifest.items.find((item) => item.name === name)
    assert.ok(entry, `${version} manifest must contain ${name}`)
    assert.match(entry.content, /^\/r\/content\/[a-f0-9]{64}\.json$/)
    const payload = await json(join(registryRoot, entry.content.slice(3))) as unknown as Omit<CustomerFixture, "entry">
    assert.equal(payload.name, name)
    assert.equal(payload.behavior?.schemaVersion, 1, `${name} fixture must carry behavior evidence`)
    assert.ok(payload.behavior.consumer.length > 0)
    fixtures.set(name, { ...payload, entry })
  }
  return fixtures
}

function releaseHeading(version: unknown) {
  assert.ok(typeof version === "string")
  return new RegExp(`^## ${version.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, "m")
}

async function pack(packageRoot: string, destination: string) {
  const before = new Set(await readdir(destination))
  await execFileAsync("pnpm", ["pack", "--pack-destination", destination], {
    cwd: packageRoot,
  })
  const created = (await readdir(destination)).filter(
    (name) => name.endsWith(".tgz") && !before.has(name)
  )
  assert.equal(created.length, 1, `expected one tarball from ${packageRoot}`)
  const tarball = join(destination, created[0]!)
  const { stdout } = await execFileAsync("tar", ["-tzf", tarball])
  assert.deepEqual(
    stdout
      .trim()
      .split(/\r?\n/)
      .map((path) => path.replace(/^package\//, ""))
      .sort(),
    ["CHANGELOG.md", "LICENSE", "README.md", "dist/index.js", "package.json"],
    `unexpected publication contents in ${tarball}`,
  )
  return tarball
}

async function withLocalRegistry<T>(run: (base: string) => Promise<T>): Promise<T> {
  const server = createServer(async (request, response) => {
    const pathname = new URL(request.url ?? "/", "http://registry.test").pathname
    if (!pathname.startsWith("/r/")) {
      response.writeHead(404).end("Not found")
      return
    }
    const registryPath = decodeURIComponent(pathname.slice(3))
    if (
      !registryPath.endsWith(".json") ||
      registryPath
        .split("/")
        .some((segment) => !segment || segment === "." || segment === "..")
    ) {
      response.writeHead(404).end("Not found")
      return
    }
    try {
      const root = registryPath.startsWith("demos/") ? builtRegistryRoot : registryRoot
      const content = await readFile(join(root, registryPath), "utf8")
      response.writeHead(200, { "content-type": "application/json" }).end(content)
    } catch {
      response.writeHead(404).end("Not found")
    }
  })
  await new Promise<void>((resolve, reject) => {
    server.once("error", reject)
    server.listen(0, "127.0.0.1", resolve)
  })
  const address = server.address()
  assert.ok(address && typeof address === "object")
  try {
    return await run(`http://127.0.0.1:${address.port}`)
  } finally {
    await new Promise<void>((resolve, reject) =>
      server.close((error) => (error ? reject(error) : resolve())),
    )
  }
}

const root = await mkdtemp(join(tmpdir(), "logic2b-release-artifacts-"))
const consumer = join(root, "consumer")
let passed = false

try {
  await access(join(builtRegistryRoot, "demos/index.json")).catch(() => {
    throw new Error("Built demo endpoints are missing. Run pnpm build before the release-artifact gate.")
  })
  const [cliSource, mcpSource] = await Promise.all([
    json(join(cliRoot, "package.json")),
    json(join(mcpRoot, "package.json")),
  ])
  assert.equal(cliSource.version, mcpSource.version, "CLI and MCP versions must match")
  for (const [name, packageRoot, manifest] of [
    ["logic2b", cliRoot, cliSource],
    ["@logic2b/mcp", mcpRoot, mcpSource],
  ] as const) {
    assert.deepEqual(manifest.files, ["dist", "CHANGELOG.md"], `${name} publish allowlist drifted`)
    assert.deepEqual(manifest.publishConfig, { access: "public" })
    assert.match(
      await readFile(join(packageRoot, "CHANGELOG.md"), "utf8"),
      releaseHeading(manifest.version),
      `${name} changelog has no entry for ${String(manifest.version)}`,
    )
  }
  const cliTarball = await pack(cliRoot, root)
  const mcpTarball = await pack(mcpRoot, root)

  await mkdir(consumer)
  await writeFile(
    join(consumer, "package.json"),
    JSON.stringify({ name: "logic2b-release-consumer", private: true }, null, 2)
  )
  await execFileAsync(
    "pnpm",
    ["add", "--prefer-offline", "--ignore-scripts", "--save-exact", cliTarball, mcpTarball],
    { cwd: consumer }
  )

  const installedCli = join(consumer, "node_modules/logic2b")
  const installedMcp = join(consumer, "node_modules/@logic2b/mcp")
  const cliManifest = await json(join(installedCli, "package.json"))
  const mcpManifest = await json(join(installedMcp, "package.json"))

  assert.equal(cliManifest.version, cliSource.version)
  assert.equal(mcpManifest.version, mcpSource.version)
  assert.deepEqual(cliManifest.bin, { logic2b: "dist/index.js" })
  assert.deepEqual(mcpManifest.bin, { "logic2b-mcp": "dist/index.js" })
  for (const packageRoot of [installedCli, installedMcp]) {
    await Promise.all(
      ["dist/index.js", "README.md", "LICENSE", "CHANGELOG.md"].map((path) =>
        access(join(packageRoot, path)),
      ),
    )
  }

  const cliEntry = join(installedCli, "dist/index.js")
  const binSuffix = process.platform === "win32" ? ".cmd" : ""
  const cliBin = join(consumer, "node_modules/.bin", `logic2b${binSuffix}`)
  const mcpBin = join(consumer, "node_modules/.bin", `logic2b-mcp${binSuffix}`)
  await Promise.all([access(cliBin), access(mcpBin)])
  const version = await execFileAsync(cliBin, ["--version"])
  assert.equal(version.stdout.trim(), cliSource.version)
  const help = await execFileAsync(cliBin, ["--help"])
  for (const command of ["init", "add", "update", "diff", "list", "status", "inspect"]) {
    assert.match(help.stdout, new RegExp(`\\b${command}\\b`))
  }
  const customerRelease = await customerFixtures(customerRegistryVersion)
  await withLocalRegistry(async (registry) => {
    const target = join(root, "generated-from-tarball")
    await execFileAsync(process.execPath, [
      cliEntry,
      "init",
      "--template",
      "vite",
      "--starter",
      "auth",
      "--name",
      "release-smoke",
      "--cwd",
      target,
      "--registry",
      registry,
      "--registry-version",
      "1.0.0-rc.16",
      "--no-install",
    ])
    await Promise.all([
      access(join(target, "package.json")),
      access(join(target, "src/main.tsx")),
      access(join(target, "src/components/login-01/login-form.tsx")),
      access(join(target, ".logic2b/manifest.json")),
      access(
        join(
          target,
          ".logic2b/base/blocks/login-01/login-form.tsx",
        ),
      ),
      access(join(target, ".logic2b/base/theme.css")),
    ])
    const oldLoginSnapshot = await readFile(join(target, ".logic2b/base/blocks/login-01/login-form.tsx"), "utf8")
    const added = await execFileAsync(process.execPath, [
      cliEntry,
      "add",
      ...customerItems,
      "--cwd",
      target,
      "--registry",
      registry,
      "--registry-version",
      customerRegistryVersion,
      "--no-install",
    ])
    const manifest = await json(join(target, ".logic2b/manifest.json")) as {
      schemaVersion: number
      registry: { url: string; requestedVersion: string; resolvedVersion: string }
      items: Record<string, { version: string; integrity: string; files: string[] }>
    }
    assert.equal(manifest.schemaVersion, 1)
    assert.deepEqual(manifest.registry, { url: registry, requestedVersion: customerRegistryVersion, resolvedVersion: customerRegistryVersion })
    for (const name of customerItems) {
      const fixture = customerRelease.get(name)!
      assert.match(added.stdout, new RegExp(`Consumer responsibilities for ${name}:`))
      for (const responsibility of fixture.behavior.consumer) assert.ok(added.stdout.includes(responsibility), `${name}: CLI omitted a consumer duty`)
      assert.deepEqual(manifest.items[name], { version: fixture.entry.version, integrity: fixture.entry.integrity, files: fixture.files.map((file) => file.path).sort() })
      for (const file of fixture.files) {
        const targetPath = file.path.replace(/^blocks\//, "src/components/")
        assert.equal(await readFile(join(target, targetPath), "utf8"), file.content, `${name} installed source differs from ${customerRegistryVersion}`)
        assert.equal(await readFile(join(target, ".logic2b/base", file.path), "utf8"), file.content, `${name} install snapshot differs from ${customerRegistryVersion}`)
      }
    }
    const inspected = await execFileAsync(process.execPath, [cliEntry, "inspect", "--cwd", target, "--json", "--details"])
    const inspection = JSON.parse(inspected.stdout)
    assert.equal(inspection.schemaVersion, 1)
    assert.equal(inspection.context.framework.name, "vite")
    assert.equal(inspection.context.sourceRoot, "src")
    assert.equal(inspection.context.locations.ui, "src/components/ui")
    assert.equal(inspection.context.registryVersion, customerRegistryVersion)
    assert.deepEqual(inspection.context.capabilities, { fileWrites: false, dependencyInstall: false, browser: false })
    assert.equal(inspection.summary.inventory.modifiedFiles, 0)
    assert.equal(inspection.summary.inventory.missingFiles, 0)
    assert.equal(inspection.summary.inventory.unknownFiles, 0)
    assert.ok(inspection.context.installed.find((item: { name: string }) => item.name === "customer-edit-01").files.length > 0)
    assert.equal(await readFile(join(target, ".logic2b/base/blocks/login-01/login-form.tsx"), "utf8"), oldLoginSnapshot, "adding customer blocks must preserve the rc.16 login snapshot")
    assert.match(added.stdout, /npm install[^\n]*\blucide-react\b/)
    const formSource = await readFile(join(target, "src/components/customer-edit-01/customer-edit-form.tsx"), "utf8")
    assert.match(formSource, /onCancelRequest\?:\s*\(\)\s*=>\s*void/)
    assert.match(formSource, /value:\s*CustomerEditValue/)
    assert.match(formSource, /onChange:\s*\(value:\s*CustomerEditValue\)\s*=>\s*void/)
    assert.match(formSource, /onSubmit:\s*\(value:\s*CustomerEditValue\)\s*=>\s*void/)
    assert.match(formSource, /onSubmit\(\{\s*\.\.\.value/)
  })

  await withLocalRegistry(async (registry) => {
    const transport = new StdioClientTransport({
      command: mcpBin,
      cwd: consumer,
      env: { LOGIC2B_REGISTRY: registry },
      stderr: "pipe",
    })
    const client = new Client({ name: "logic2b-release-verifier", version: "1.0.0" })
    try {
      await client.connect(transport)
      assert.deepEqual(client.getServerVersion(), {
        name: "logic2b-ui",
        version: mcpSource.version,
      })
      const { tools } = await client.listTools()
      assert.deepEqual(
        tools.map((tool) => tool.name).sort(),
        [
          "add_command",
          "apply_preset",
          "contrast_audit",
          "decode_preset",
          "export_tokens",
          "get_changelog",
          "get_component",
          "get_demo",
          "get_theme",
          "inspect_project",
          "install_plan",
          "lint_theme",
          "list_components",
          "list_presets",
          "list_registry_versions",
          "scaffold_plan",
          "search_components",
        ]
      )
      for (const tool of tools) {
        assert.equal(tool.outputSchema?.type, "object", `${tool.name} output schema missing`)
        assert.equal(tool.annotations?.readOnlyHint, true)
        assert.equal(tool.annotations?.destructiveHint, false)
      }
      const preset = encodePreset(DEFAULT_CONFIG)
      const theme = await json(join(registryRoot, "theme.json"))
      // An omitted version must resolve the published default channel exactly.
      const versions = (await json(join(registryRoot, "versions.json"))) as {
        channels: Record<string, string>
      }
      const defaultVersion = versions.channels[REGISTRY_DEFAULT_CHANNEL]
      assert.ok(defaultVersion, `registry fixture publishes no "${REGISTRY_DEFAULT_CHANNEL}" channel`)
      const css = (theme.files as Array<{ content: string }>)[0]!.content
      const cases: Array<[string, Record<string, unknown>]> = [
        ["inspect_project", { snapshot: { schemaVersion: 1, configs: [], capabilities: { fileWrites: false, dependencyInstall: false, browser: false } } }],
        ["inspect_project", { snapshot: { schemaVersion: 1, configs: [], capabilities: { fileWrites: false, dependencyInstall: false, browser: false } }, details: true }],
        ["list_components", {}],
        ["list_presets", {}],
        ["search_components", { query: "button" }],
        ["get_component", { name: "button", version: "1.0.0-rc.16" }],
        ["list_registry_versions", {}],
        ["get_changelog", { name: "button" }],
        ["get_demo", { name: "button" }],
        ["add_command", { items: ["button"] }],
        ["install_plan", { items: ["button"], version: "1.0.0-rc.16" }],
        ["scaffold_plan", { framework: "vite", starter: "auth", version: "1.0.0-rc.16" }],
        ["get_theme", {}],
        ["export_tokens", { preset }],
        ["decode_preset", { preset }],
        ["apply_preset", { preset, css }],
        ["contrast_audit", { preset }],
        ["contrast_audit", { tokens: { foreground: "oklch(0 0 0)", background: "oklch(1 0 0)" } }],
        ["lint_theme", { css, preset }],
      ]
      for (const [name, args] of cases) {
        // The official client validates structuredContent against tools/list.
        const result = await client.callTool({ name, arguments: args })
        assert.ok(!result.isError, `${name}: ${JSON.stringify(result.content)}`)
        const content = result.content as Array<{ type: string; text?: string }>
        assert.equal(content[0]?.type, "text")
        assert.deepEqual(result.structuredContent, JSON.parse(content[0]!.text!))
        const versioned = result.structuredContent as {
          requestedVersion?: string
          registryVersion?: string
          commands?: Record<string, string>
        }
        if (["list_components", "search_components", "add_command", "get_theme"].includes(name)) {
          assert.equal(versioned.requestedVersion, REGISTRY_DEFAULT_CHANNEL, `${name} default selector`)
          assert.equal(versioned.registryVersion, defaultVersion, `${name} resolved default release`)
        }
        if (name === "add_command") {
          for (const [manager, runner] of Object.entries(PACKAGE_RUNNERS)) {
            assert.equal(
              versioned.commands?.[manager],
              `${runner} ${CLI_PACKAGE_SELECTOR} add button --registry-version ${defaultVersion}`
            )
          }
        }
      }
      // Exercise the actual packed behavior payloads through the official
      // client, including its output-schema validation and JSON text fallback.
      async function callPackedTool(name: string, args: Record<string, unknown>) {
        const result = await client.callTool({ name, arguments: args })
        assert.ok(!result.isError, `${name}: ${JSON.stringify(result.content)}`)
        const content = result.content as Array<{ type: string; text?: string }>
        assert.equal(content[0]?.type, "text")
        assert.deepEqual(result.structuredContent, JSON.parse(content[0]!.text!))
        return result.structuredContent as Record<string, unknown>
      }
      const defaultCustomers = defaultVersion === customerRegistryVersion ? customerRelease : await customerFixtures(defaultVersion)
      for (const name of customerItems) {
        for (const selector of [customerRegistryVersion, undefined]) {
          const expected = (selector ? customerRelease : defaultCustomers).get(name)!
          const item = await callPackedTool("get_component", { name, ...(selector ? { version: selector } : {}) })
          assert.equal(item.registryVersion, selector ?? defaultVersion)
          assert.equal(item.integrity, expected.entry.integrity)
          assert.deepEqual(item.behavior, expected.behavior, `${name}: packed get_component lost behavior metadata`)
          assert.deepEqual(item.files, expected.files, `${name}: packed get_component source drifted`)
        }
      }
      const customerPlan = await callPackedTool("install_plan", { items: [...customerItems], version: customerRegistryVersion }) as {
        requestedVersion: string
        registryVersion: string
        items: Array<{ name: string; requested: boolean; integrity: string; behavior?: unknown }>
        files: Array<{ path: string; content: string }>
        notes: string[]
        npmDependencies: string[]
      }
      assert.equal(customerPlan.requestedVersion, customerRegistryVersion)
      assert.equal(customerPlan.registryVersion, customerRegistryVersion)
      assert.ok(customerPlan.npmDependencies.includes("lucide-react"))
      for (const name of customerItems) {
        const fixture = customerRelease.get(name)!
        const planned = customerPlan.items.find((item) => item.name === name)
        assert.equal(planned?.requested, true)
        assert.equal(planned?.integrity, fixture.entry.integrity)
        assert.deepEqual(planned?.behavior, fixture.behavior, `${name}: packed install_plan lost behavior metadata`)
        for (const responsibility of fixture.behavior.consumer) {
          assert.ok(customerPlan.notes.some((note) => note.includes(name) && note.includes(responsibility)), `${name}: packed install_plan omitted a consumer duty`)
        }
        for (const file of fixture.files) {
          assert.deepEqual(customerPlan.files.find((planned) => planned.path === file.path.replace(/^blocks\//, "src/components/")), { path: file.path.replace(/^blocks\//, "src/components/"), content: file.content })
        }
      }
      const failure = await client.callTool({ name: "decode_preset", arguments: { preset: "invalid" } })
      assert.equal(failure.isError, true)
      assert.equal(failure.structuredContent, undefined)
      // Protocol failures stay distinguishable from execution failures over stdio.
      for (const [name, args] of [
        ["nope", {}],
        ["search_components", { query: "x", limit: 0 }],
        ["install_plan", { items: ["button", "button"] }],
      ] as const) {
        await assert.rejects(
          () => client.callTool({ name, arguments: args as Record<string, unknown> }),
          (error: unknown) => error instanceof McpError && error.code === -32602,
          `${name}: expected JSON-RPC invalid params`
        )
      }
      await client.ping()
    } finally {
      await client.close()
    }
  })

  passed = true
  console.log(`✓ logic2b@${cliSource.version}: packed, consumer-installed, help/version/inspect/rc.16 scaffold and rc.17 customer installs verified`)
  console.log(`✓ @logic2b/mcp@${mcpSource.version}: packed, consumer-installed, all 17 tool output contracts, project inspection and customer behavior plans verified over stdio`)
} finally {
  if (passed) {
    await rm(root, { recursive: true, force: true })
  } else {
    console.error(`Release artifact fixture kept for inspection: ${root}`)
  }
}
