import { readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { extractApiContracts } from "./extract-api.ts"

export const apiGeneratedPath = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../api.generated.ts",
)

export async function generatedApiSource(): Promise<string> {
  const contracts = await extractApiContracts()
  return [
    "// Generated by scripts/generate-api.ts from src/ui/*.tsx. Do not edit by hand.",
    'import type { RegistryApiContracts } from "./types.ts"',
    "",
    `export const API_CONTRACTS: RegistryApiContracts = ${JSON.stringify(contracts, null, 2)}`,
    "",
  ].join("\n")
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const next = await generatedApiSource()
  const current = await readFile(apiGeneratedPath, "utf8").catch(() => "")
  if (current !== next) await writeFile(apiGeneratedPath, next)
  console.log(`✓ generated API contracts → ${apiGeneratedPath}`)
}
