// Generated by scripts/generate-api.ts from src/ui/*.tsx. Do not edit by hand.
import type { RegistryApiContracts } from "./types.ts"

export const API_CONTRACTS: RegistryApiContracts = {
  "accordion": {
    "source": "src/ui/accordion.tsx",
    "exports": [
      {
        "name": "Accordion",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AccordionPrimitive.Root>"
      },
      {
        "name": "AccordionItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AccordionPrimitive.Item>"
      },
      {
        "name": "AccordionTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AccordionPrimitive.Trigger>"
      },
      {
        "name": "AccordionContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AccordionPrimitive.Content>"
      }
    ]
  },
  "alert-dialog": {
    "source": "src/ui/alert-dialog.tsx",
    "exports": [
      {
        "name": "AlertDialog",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AlertDialogPrimitive.Root>"
      },
      {
        "name": "AlertDialogPortal",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AlertDialogPrimitive.Portal>"
      },
      {
        "name": "AlertDialogOverlay",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AlertDialogPrimitive.Overlay>"
      },
      {
        "name": "AlertDialogTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AlertDialogPrimitive.Trigger>"
      },
      {
        "name": "AlertDialogContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AlertDialogPrimitive.Content>"
      },
      {
        "name": "AlertDialogHeader",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "AlertDialogFooter",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "AlertDialogTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AlertDialogPrimitive.Title>"
      },
      {
        "name": "AlertDialogDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AlertDialogPrimitive.Description>"
      },
      {
        "name": "AlertDialogAction",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AlertDialogPrimitive.Action>"
      },
      {
        "name": "AlertDialogCancel",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AlertDialogPrimitive.Cancel>"
      }
    ]
  },
  "alert": {
    "source": "src/ui/alert.tsx",
    "exports": [
      {
        "name": "Alert",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & VariantProps<typeof alertVariants>",
        "props": [
          {
            "name": "variant",
            "type": "null | \"default\" | \"destructive\"",
            "required": false
          }
        ]
      },
      {
        "name": "AlertTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "AlertDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      }
    ]
  },
  "aspect-ratio": {
    "source": "src/ui/aspect-ratio.tsx",
    "exports": [
      {
        "name": "AspectRatio",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AspectRatioPrimitive.Root>"
      }
    ]
  },
  "autocomplete": {
    "source": "src/ui/autocomplete.tsx",
    "exports": [
      {
        "name": "AutocompleteProps",
        "kind": "type",
        "definition": "interface AutocompleteProps extends Omit< React.ComponentProps<\"input\">, \"value\" | \"defaultValue\" | \"onChange\" > { /** The suggestion list, filtered against what the user types. */ options: string[] value?: string defaultValue?: string onValueChange?: (value: string) => void /** Shown when nothing matches. Default `\"No results.\"`. */ emptyMessage?: string }"
      },
      {
        "name": "Autocomplete",
        "kind": "component",
        "description": "A free-text input with a filtered suggestion list — the editable ARIA combobox pattern. Unlike a select-style combobox it accepts arbitrary text; the list just offers matches. Fully keyboard-driven (↑/↓ to move, Enter to pick, Esc to close) and dependency-free.",
        "propsType": "AutocompleteProps",
        "props": [
          {
            "name": "options",
            "type": "string[]",
            "required": true,
            "description": "The suggestion list, filtered against what the user types."
          },
          {
            "name": "value",
            "type": "string",
            "required": false
          },
          {
            "name": "defaultValue",
            "type": "string",
            "required": false
          },
          {
            "name": "onValueChange",
            "type": "(value: string) => void",
            "required": false
          },
          {
            "name": "emptyMessage",
            "type": "string",
            "required": false,
            "default": "\"No results.\"",
            "description": "Shown when nothing matches. Default `\"No results.\"`."
          }
        ]
      }
    ]
  },
  "avatar": {
    "source": "src/ui/avatar.tsx",
    "exports": [
      {
        "name": "Avatar",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AvatarPrimitive.Root>"
      },
      {
        "name": "AvatarImage",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AvatarPrimitive.Image>"
      },
      {
        "name": "AvatarFallback",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof AvatarPrimitive.Fallback>"
      }
    ]
  },
  "badge": {
    "source": "src/ui/badge.tsx",
    "exports": [
      {
        "name": "Badge",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\"> & VariantProps<typeof badgeVariants> & { asChild?: boolean }",
        "props": [
          {
            "name": "variant",
            "type": "null | \"default\" | \"destructive\" | \"secondary\" | \"outline\"",
            "required": false
          },
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false"
          }
        ]
      },
      {
        "name": "badgeVariants",
        "kind": "utility",
        "signature": "(props?: (ConfigVariants<{ variant: { default: string; secondary: string; destructive: string; outline: string; }; }> & ClassProp) | undefined): string"
      }
    ]
  },
  "breadcrumb": {
    "source": "src/ui/breadcrumb.tsx",
    "exports": [
      {
        "name": "Breadcrumb",
        "kind": "component",
        "propsType": "React.ComponentProps<\"nav\">"
      },
      {
        "name": "BreadcrumbList",
        "kind": "component",
        "propsType": "React.ComponentProps<\"ol\">"
      },
      {
        "name": "BreadcrumbItem",
        "kind": "component",
        "propsType": "React.ComponentProps<\"li\">"
      },
      {
        "name": "BreadcrumbLink",
        "kind": "component",
        "propsType": "React.ComponentProps<\"a\"> & { asChild?: boolean }",
        "props": [
          {
            "name": "asChild",
            "type": "boolean",
            "required": false
          }
        ]
      },
      {
        "name": "BreadcrumbPage",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      },
      {
        "name": "BreadcrumbSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<\"li\">"
      },
      {
        "name": "BreadcrumbEllipsis",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      }
    ]
  },
  "button-group": {
    "source": "src/ui/button-group.tsx",
    "exports": [
      {
        "name": "ButtonGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & { orientation?: \"horizontal\" | \"vertical\" }",
        "props": [
          {
            "name": "orientation",
            "type": "\"horizontal\" | \"vertical\"",
            "required": false,
            "default": "\"horizontal\""
          }
        ]
      },
      {
        "name": "ButtonGroupText",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & { asChild?: boolean }",
        "props": [
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false"
          }
        ]
      },
      {
        "name": "ButtonGroupSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Separator>",
        "props": [
          {
            "name": "orientation",
            "type": "\"horizontal\" | \"vertical\"",
            "required": false,
            "default": "\"vertical\"",
            "description": "Either `vertical` or `horizontal`. Defaults to `horizontal`."
          }
        ]
      }
    ]
  },
  "button": {
    "source": "src/ui/button.tsx",
    "exports": [
      {
        "name": "Button",
        "kind": "component",
        "propsType": "React.ComponentProps<\"button\"> & VariantProps<typeof buttonVariants> & { asChild?: boolean }",
        "props": [
          {
            "name": "variant",
            "type": "null | \"link\" | \"default\" | \"destructive\" | \"secondary\" | \"outline\" | \"ghost\"",
            "required": false
          },
          {
            "name": "size",
            "type": "null | \"default\" | \"sm\" | \"lg\" | \"icon\"",
            "required": false
          },
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false"
          }
        ]
      },
      {
        "name": "buttonVariants",
        "kind": "utility",
        "signature": "(props?: (ConfigVariants<{ variant: { default: string; destructive: string; outline: string; secondary: string; ghost: string; link: string; }; size: { default: string; sm: string; lg: string; icon: string; }; }> & ClassProp) | undefined): string"
      }
    ]
  },
  "calendar": {
    "source": "src/ui/calendar.tsx",
    "exports": [
      {
        "name": "Calendar",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DayPicker> & { buttonVariant?: React.ComponentProps<typeof Button>[\"variant\"] }",
        "props": [
          {
            "name": "showOutsideDays",
            "type": "boolean",
            "required": false,
            "default": "true",
            "description": "Show the outside days (days falling in the next or the previous month). **Note:** when a {@link broadcastCalendar} is set, this prop defaults to true."
          },
          {
            "name": "captionLayout",
            "type": "\"label\" | \"dropdown\" | \"dropdown-months\" | \"dropdown-years\"",
            "required": false,
            "default": "\"label\"",
            "description": "Show dropdowns to navigate between months or years. - `label`: Displays the month and year as a label. Default value. - `dropdown`: Displays dropdowns for both month and year navigation. - `dropdown-months`: Displays a dropdown only for the month navigation. - `dropdown-years`: Displays a dropdown only for the year navigation. **Note:** By default, showing the dropdown will set the {@link startMonth} to 100 years ago and {@link endMonth} to the end of the current year. You can override this behavior by explicitly setting `startMonth` and `endMonth`."
          },
          {
            "name": "buttonVariant",
            "type": "React.ComponentProps<typeof Button>[\"variant\"]",
            "required": false,
            "default": "\"ghost\""
          }
        ]
      },
      {
        "name": "CalendarDayButton",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DayButton>"
      }
    ]
  },
  "card": {
    "source": "src/ui/card.tsx",
    "exports": [
      {
        "name": "Card",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "CardHeader",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "CardFooter",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "CardTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "CardAction",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "CardDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "CardContent",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      }
    ]
  },
  "carousel": {
    "source": "src/ui/carousel.tsx",
    "exports": [
      {
        "name": "CarouselApi",
        "kind": "type",
        "definition": "type CarouselApi = UseEmblaCarouselType[1]"
      },
      {
        "name": "Carousel",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & CarouselProps",
        "props": [
          {
            "name": "orientation",
            "type": "\"horizontal\" | \"vertical\"",
            "required": false,
            "default": "\"horizontal\""
          },
          {
            "name": "opts",
            "type": "CarouselOptions",
            "required": false
          },
          {
            "name": "setApi",
            "type": "(api: CarouselApi) => void",
            "required": false
          },
          {
            "name": "plugins",
            "type": "CarouselPlugin",
            "required": false
          }
        ]
      },
      {
        "name": "CarouselContent",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "CarouselItem",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "CarouselPrevious",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Button>",
        "props": [
          {
            "name": "variant",
            "type": "null | \"link\" | \"default\" | \"destructive\" | \"secondary\" | \"outline\" | \"ghost\"",
            "required": false,
            "default": "\"outline\""
          },
          {
            "name": "size",
            "type": "null | \"default\" | \"sm\" | \"lg\" | \"icon\"",
            "required": false,
            "default": "\"icon\""
          }
        ]
      },
      {
        "name": "CarouselNext",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Button>",
        "props": [
          {
            "name": "variant",
            "type": "null | \"link\" | \"default\" | \"destructive\" | \"secondary\" | \"outline\" | \"ghost\"",
            "required": false,
            "default": "\"outline\""
          },
          {
            "name": "size",
            "type": "null | \"default\" | \"sm\" | \"lg\" | \"icon\"",
            "required": false,
            "default": "\"icon\""
          }
        ]
      }
    ]
  },
  "chart": {
    "source": "src/ui/chart.tsx",
    "exports": [
      {
        "name": "ChartConfig",
        "kind": "type",
        "definition": "type ChartConfig = { [k in string]: { label?: React.ReactNode icon?: React.ComponentType } & ( | { color?: string; theme?: never } | { color?: never; theme: Record<keyof typeof THEMES, string> } ) }"
      },
      {
        "name": "ChartContainer",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & { config: ChartConfig children: React.ComponentProps< typeof RechartsPrimitive.ResponsiveContainer >[\"children\"] }",
        "props": [
          {
            "name": "children",
            "type": "React.ComponentProps< typeof RechartsPrimitive.ResponsiveContainer >[\"children\"]",
            "required": true
          },
          {
            "name": "config",
            "type": "ChartConfig",
            "required": true
          }
        ]
      },
      {
        "name": "ChartTooltip",
        "kind": "component",
        "aliasOf": "RechartsPrimitive.Tooltip"
      },
      {
        "name": "ChartTooltipContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof RechartsPrimitive.Tooltip> & React.ComponentProps<\"div\"> & { hideLabel?: boolean hideIndicator?: boolean indicator?: \"line\" | \"dot\" | \"dashed\" nameKey?: string labelKey?: string } & Omit< RechartsPrimitive.DefaultTooltipContentProps< TooltipValueType, TooltipNameType >, \"accessibilityLayer\" >",
        "props": [
          {
            "name": "indicator",
            "type": "\"line\" | \"dot\" | \"dashed\"",
            "required": false,
            "default": "\"dot\""
          },
          {
            "name": "hideLabel",
            "type": "boolean",
            "required": false,
            "default": "false"
          },
          {
            "name": "hideIndicator",
            "type": "boolean",
            "required": false,
            "default": "false"
          },
          {
            "name": "nameKey",
            "type": "string",
            "required": false
          },
          {
            "name": "labelKey",
            "type": "string",
            "required": false
          }
        ]
      },
      {
        "name": "ChartLegend",
        "kind": "component",
        "aliasOf": "RechartsPrimitive.Legend"
      },
      {
        "name": "ChartLegendContent",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & { hideIcon?: boolean nameKey?: string } & RechartsPrimitive.DefaultLegendContentProps",
        "props": [
          {
            "name": "hideIcon",
            "type": "boolean",
            "required": false,
            "default": "false"
          },
          {
            "name": "verticalAlign",
            "type": "\"top\" | \"bottom\" | \"middle\"",
            "required": false,
            "default": "\"bottom\"",
            "description": "Vertical alignment of the whole Legend container: - `bottom`: shows the Legend below chart, and chart height reduces automatically to make space for it. - `top`: shows the Legend above chart, and chart height reduces automatically. - `middle`: shows the Legend in the middle of chart, covering other content, and chart height remains unchanged. The exact behavior changes depending on `align` prop."
          },
          {
            "name": "nameKey",
            "type": "string",
            "required": false
          }
        ]
      },
      {
        "name": "ChartStyle",
        "kind": "component",
        "propsType": "{ id: string; config: ChartConfig }",
        "props": [
          {
            "name": "id",
            "type": "string",
            "required": true
          },
          {
            "name": "config",
            "type": "ChartConfig",
            "required": true
          }
        ]
      }
    ]
  },
  "checkbox": {
    "source": "src/ui/checkbox.tsx",
    "exports": [
      {
        "name": "Checkbox",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CheckboxPrimitive.Root>"
      }
    ]
  },
  "code-block": {
    "source": "src/ui/code-block.tsx",
    "exports": [
      {
        "name": "CodeBlockProps",
        "kind": "type",
        "definition": "interface CodeBlockProps extends Omit<React.ComponentProps<\"div\">, \"children\"> { /** The code to render and copy. */ code: string /** Optional language label shown in the header (display only — no highlighting). */ language?: string }"
      },
      {
        "name": "CodeBlock",
        "kind": "component",
        "description": "A styled code container with a one-click copy button. Dependency-free (no syntax highlighter): renders the code verbatim in a `<pre>` and copies it via the Clipboard API, with a copied-state affordance.",
        "propsType": "CodeBlockProps",
        "props": [
          {
            "name": "code",
            "type": "string",
            "required": true,
            "description": "The code to render and copy."
          },
          {
            "name": "language",
            "type": "string",
            "required": false,
            "description": "Optional language label shown in the header (display only — no highlighting)."
          }
        ]
      }
    ]
  },
  "collapsible": {
    "source": "src/ui/collapsible.tsx",
    "exports": [
      {
        "name": "Collapsible",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CollapsiblePrimitive.Root>"
      },
      {
        "name": "CollapsibleTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CollapsiblePrimitive.CollapsibleTrigger>"
      },
      {
        "name": "CollapsibleContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CollapsiblePrimitive.CollapsibleContent>"
      }
    ]
  },
  "color-picker": {
    "source": "src/ui/color-picker.tsx",
    "exports": [
      {
        "name": "ColorPickerProps",
        "kind": "type",
        "definition": "interface ColorPickerProps extends Omit<React.ComponentProps<\"div\">, \"onChange\" | \"defaultValue\"> { /** Current color as a `#rrggbb` hex string (controlled). */ value?: string defaultValue?: string onValueChange?: (hex: string) => void }"
      },
      {
        "name": "ColorPicker",
        "kind": "component",
        "description": "A self-contained HSV color picker: a saturation/value area, a hue slider and a hex input. Controlled via `value`/`onValueChange` or uncontrolled via `defaultValue`. Emits `#rrggbb`. Zero dependencies.",
        "propsType": "ColorPickerProps",
        "props": [
          {
            "name": "value",
            "type": "string",
            "required": false,
            "description": "Current color as a `#rrggbb` hex string (controlled)."
          },
          {
            "name": "defaultValue",
            "type": "string",
            "required": false
          },
          {
            "name": "onValueChange",
            "type": "(hex: string) => void",
            "required": false
          }
        ]
      }
    ]
  },
  "command": {
    "source": "src/ui/command.tsx",
    "exports": [
      {
        "name": "Command",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CommandPrimitive>"
      },
      {
        "name": "CommandDialog",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Dialog> & { title?: string description?: string className?: string showCloseButton?: boolean }",
        "props": [
          {
            "name": "title",
            "type": "string",
            "required": false,
            "default": "\"Command Palette\""
          },
          {
            "name": "description",
            "type": "string",
            "required": false,
            "default": "\"Search for a command to run...\""
          },
          {
            "name": "showCloseButton",
            "type": "boolean",
            "required": false,
            "default": "true"
          }
        ]
      },
      {
        "name": "CommandInput",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CommandPrimitive.Input>"
      },
      {
        "name": "CommandList",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CommandPrimitive.List>"
      },
      {
        "name": "CommandEmpty",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CommandPrimitive.Empty>"
      },
      {
        "name": "CommandGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CommandPrimitive.Group>"
      },
      {
        "name": "CommandItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CommandPrimitive.Item>"
      },
      {
        "name": "CommandShortcut",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      },
      {
        "name": "CommandSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof CommandPrimitive.Separator>"
      }
    ]
  },
  "context-menu": {
    "source": "src/ui/context-menu.tsx",
    "exports": [
      {
        "name": "ContextMenu",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.Root>"
      },
      {
        "name": "ContextMenuTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.Trigger>"
      },
      {
        "name": "ContextMenuContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.Content>"
      },
      {
        "name": "ContextMenuItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.Item> & { inset?: boolean variant?: \"default\" | \"destructive\" }",
        "props": [
          {
            "name": "inset",
            "type": "boolean",
            "required": false
          },
          {
            "name": "variant",
            "type": "\"default\" | \"destructive\"",
            "required": false,
            "default": "\"default\""
          }
        ]
      },
      {
        "name": "ContextMenuCheckboxItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.CheckboxItem>"
      },
      {
        "name": "ContextMenuRadioItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.RadioItem>"
      },
      {
        "name": "ContextMenuLabel",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.Label> & { inset?: boolean }",
        "props": [
          {
            "name": "inset",
            "type": "boolean",
            "required": false
          }
        ]
      },
      {
        "name": "ContextMenuSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.Separator>"
      },
      {
        "name": "ContextMenuShortcut",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      },
      {
        "name": "ContextMenuGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.Group>"
      },
      {
        "name": "ContextMenuPortal",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.Portal>"
      },
      {
        "name": "ContextMenuSub",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.Sub>"
      },
      {
        "name": "ContextMenuSubContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.SubContent>"
      },
      {
        "name": "ContextMenuSubTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.SubTrigger> & { inset?: boolean }",
        "props": [
          {
            "name": "inset",
            "type": "boolean",
            "required": false
          }
        ]
      },
      {
        "name": "ContextMenuRadioGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ContextMenuPrimitive.RadioGroup>"
      }
    ]
  },
  "dialog": {
    "source": "src/ui/dialog.tsx",
    "exports": [
      {
        "name": "Dialog",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DialogPrimitive.Root>"
      },
      {
        "name": "DialogClose",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DialogPrimitive.Close>"
      },
      {
        "name": "DialogContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DialogPrimitive.Content> & { showCloseButton?: boolean }",
        "props": [
          {
            "name": "showCloseButton",
            "type": "boolean",
            "required": false,
            "default": "true"
          }
        ]
      },
      {
        "name": "DialogDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DialogPrimitive.Description>"
      },
      {
        "name": "DialogFooter",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "DialogHeader",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "DialogOverlay",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DialogPrimitive.Overlay>"
      },
      {
        "name": "DialogPortal",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DialogPrimitive.Portal>"
      },
      {
        "name": "DialogTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DialogPrimitive.Title>"
      },
      {
        "name": "DialogTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DialogPrimitive.Trigger>"
      }
    ]
  },
  "drawer": {
    "source": "src/ui/drawer.tsx",
    "exports": [
      {
        "name": "Drawer",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DrawerPrimitive.Root>"
      },
      {
        "name": "DrawerPortal",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DrawerPrimitive.Portal>"
      },
      {
        "name": "DrawerOverlay",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DrawerPrimitive.Overlay>"
      },
      {
        "name": "DrawerTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DrawerPrimitive.Trigger>"
      },
      {
        "name": "DrawerClose",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DrawerPrimitive.Close>"
      },
      {
        "name": "DrawerContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DrawerPrimitive.Content>"
      },
      {
        "name": "DrawerHeader",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "DrawerFooter",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "DrawerTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DrawerPrimitive.Title>"
      },
      {
        "name": "DrawerDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DrawerPrimitive.Description>"
      }
    ]
  },
  "dropdown-menu": {
    "source": "src/ui/dropdown-menu.tsx",
    "exports": [
      {
        "name": "DropdownMenu",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.Root>"
      },
      {
        "name": "DropdownMenuPortal",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.Portal>"
      },
      {
        "name": "DropdownMenuTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.Trigger>"
      },
      {
        "name": "DropdownMenuContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.Content>",
        "props": [
          {
            "name": "sideOffset",
            "type": "number",
            "required": false,
            "default": "4"
          }
        ]
      },
      {
        "name": "DropdownMenuGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.Group>"
      },
      {
        "name": "DropdownMenuLabel",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.Label> & { inset?: boolean }",
        "props": [
          {
            "name": "inset",
            "type": "boolean",
            "required": false
          }
        ]
      },
      {
        "name": "DropdownMenuItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.Item> & { inset?: boolean variant?: \"default\" | \"destructive\" }",
        "props": [
          {
            "name": "inset",
            "type": "boolean",
            "required": false
          },
          {
            "name": "variant",
            "type": "\"default\" | \"destructive\"",
            "required": false,
            "default": "\"default\""
          }
        ]
      },
      {
        "name": "DropdownMenuCheckboxItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.CheckboxItem>"
      },
      {
        "name": "DropdownMenuRadioGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.RadioGroup>"
      },
      {
        "name": "DropdownMenuRadioItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.RadioItem>"
      },
      {
        "name": "DropdownMenuSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.Separator>"
      },
      {
        "name": "DropdownMenuShortcut",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      },
      {
        "name": "DropdownMenuSub",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.Sub>"
      },
      {
        "name": "DropdownMenuSubTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.SubTrigger> & { inset?: boolean }",
        "props": [
          {
            "name": "inset",
            "type": "boolean",
            "required": false
          }
        ]
      },
      {
        "name": "DropdownMenuSubContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof DropdownMenuPrimitive.SubContent>"
      }
    ]
  },
  "empty": {
    "source": "src/ui/empty.tsx",
    "exports": [
      {
        "name": "Empty",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "EmptyHeader",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "EmptyTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "EmptyDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<\"p\">"
      },
      {
        "name": "EmptyContent",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "EmptyMedia",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & VariantProps<typeof emptyMediaVariants>",
        "props": [
          {
            "name": "variant",
            "type": "null | \"default\" | \"icon\"",
            "required": false,
            "default": "\"default\""
          }
        ]
      }
    ]
  },
  "field": {
    "source": "src/ui/field.tsx",
    "exports": [
      {
        "name": "Field",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & VariantProps<typeof fieldVariants>",
        "props": [
          {
            "name": "orientation",
            "type": "null | \"horizontal\" | \"vertical\" | \"responsive\"",
            "required": false,
            "default": "\"vertical\""
          }
        ]
      },
      {
        "name": "FieldLabel",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Label>"
      },
      {
        "name": "FieldDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<\"p\">"
      },
      {
        "name": "FieldError",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & { errors?: Array<{ message?: string } | undefined> }",
        "props": [
          {
            "name": "errors",
            "type": "Array<{ message?: string } | undefined>",
            "required": false
          }
        ]
      },
      {
        "name": "FieldGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "FieldSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "FieldSet",
        "kind": "component",
        "propsType": "React.ComponentProps<\"fieldset\">"
      },
      {
        "name": "FieldLegend",
        "kind": "component",
        "propsType": "React.ComponentProps<\"legend\"> & { variant?: \"legend\" | \"label\" }",
        "props": [
          {
            "name": "variant",
            "type": "\"legend\" | \"label\"",
            "required": false,
            "default": "\"legend\""
          }
        ]
      },
      {
        "name": "FieldContent",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "FieldTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      }
    ]
  },
  "file-dropzone": {
    "source": "src/ui/file-dropzone.tsx",
    "exports": [
      {
        "name": "FileDropzoneProps",
        "kind": "type",
        "definition": "interface FileDropzoneProps extends Omit<React.ComponentProps<\"div\">, \"onDrop\" | \"children\"> { /** Called with the accepted files when they are dropped or selected. */ onFiles?: (files: File[]) => void /** `accept` attribute forwarded to the file input (e.g. `\"image/*\"`). */ accept?: string /** Allow selecting more than one file. Default `false`. */ multiple?: boolean disabled?: boolean /** Accessible name for the native file input. Default `\"Upload files\"`. */ inputLabel?: string /** Replace the default icon/prompt with your own content. */ children?: React.ReactNode }"
      },
      {
        "name": "FileDropzone",
        "kind": "component",
        "description": "A drag-and-drop file surface with click / keyboard to browse. Native DnD (no dependencies): highlights while a file is dragged over it and calls `onFiles` with the dropped or selected files. Rendering the file list is left to the consumer.",
        "propsType": "FileDropzoneProps",
        "props": [
          {
            "name": "onFiles",
            "type": "(files: File[]) => void",
            "required": false,
            "description": "Called with the accepted files when they are dropped or selected."
          },
          {
            "name": "accept",
            "type": "string",
            "required": false,
            "description": "`accept` attribute forwarded to the file input (e.g. `\"image/*\"`)."
          },
          {
            "name": "multiple",
            "type": "boolean",
            "required": false,
            "default": "false",
            "description": "Allow selecting more than one file. Default `false`."
          },
          {
            "name": "disabled",
            "type": "boolean",
            "required": false
          },
          {
            "name": "inputLabel",
            "type": "string",
            "required": false,
            "default": "\"Upload files\"",
            "description": "Accessible name for the native file input. Default `\"Upload files\"`."
          },
          {
            "name": "children",
            "type": "React.ReactNode",
            "required": false,
            "description": "Replace the default icon/prompt with your own content."
          }
        ]
      }
    ]
  },
  "form": {
    "source": "src/ui/form.tsx",
    "exports": [
      {
        "name": "useFormField",
        "kind": "hook",
        "signature": "(): { invalid: boolean; isDirty: boolean; isTouched: boolean; isValidating: boolean; error?: FieldError; id: string; name: string; formItemId: string; formDescriptionId: string; formMessageId: string; }"
      },
      {
        "name": "Form",
        "kind": "component",
        "aliasOf": "FormProvider"
      },
      {
        "name": "FormItem",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "FormLabel",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Label>"
      },
      {
        "name": "FormControl",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Slot.Root>"
      },
      {
        "name": "FormDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<\"p\">"
      },
      {
        "name": "FormMessage",
        "kind": "component",
        "propsType": "React.ComponentProps<\"p\">"
      },
      {
        "name": "FormField",
        "kind": "component",
        "propsType": "ControllerProps<TFieldValues, TName>"
      }
    ]
  },
  "hover-card": {
    "source": "src/ui/hover-card.tsx",
    "exports": [
      {
        "name": "HoverCard",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof HoverCardPrimitive.Root>"
      },
      {
        "name": "HoverCardTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof HoverCardPrimitive.Trigger>"
      },
      {
        "name": "HoverCardContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof HoverCardPrimitive.Content>",
        "props": [
          {
            "name": "align",
            "type": "\"center\" | \"end\" | \"start\"",
            "required": false,
            "default": "\"center\""
          },
          {
            "name": "sideOffset",
            "type": "number",
            "required": false,
            "default": "4"
          }
        ]
      }
    ]
  },
  "input-group": {
    "source": "src/ui/input-group.tsx",
    "exports": [
      {
        "name": "InputGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "InputGroupAddon",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & VariantProps<typeof inputGroupAddonVariants>",
        "props": [
          {
            "name": "align",
            "type": "null | \"inline-start\" | \"inline-end\" | \"block-start\" | \"block-end\"",
            "required": false,
            "default": "\"inline-start\""
          }
        ]
      },
      {
        "name": "InputGroupButton",
        "kind": "component",
        "propsType": "Omit<React.ComponentProps<typeof Button>, \"size\"> & VariantProps<typeof inputGroupButtonVariants>",
        "props": [
          {
            "name": "type",
            "type": "\"button\" | \"submit\" | \"reset\"",
            "required": false,
            "default": "\"button\""
          },
          {
            "name": "variant",
            "type": "null | \"link\" | \"default\" | \"destructive\" | \"secondary\" | \"outline\" | \"ghost\"",
            "required": false,
            "default": "\"ghost\""
          },
          {
            "name": "size",
            "type": "null | \"sm\" | \"xs\" | \"icon-xs\" | \"icon-sm\"",
            "required": false,
            "default": "\"xs\""
          }
        ]
      },
      {
        "name": "InputGroupText",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      },
      {
        "name": "InputGroupInput",
        "kind": "component",
        "propsType": "React.ComponentProps<\"input\">"
      },
      {
        "name": "InputGroupTextarea",
        "kind": "component",
        "propsType": "React.ComponentProps<\"textarea\">"
      }
    ]
  },
  "input-otp": {
    "source": "src/ui/input-otp.tsx",
    "exports": [
      {
        "name": "InputOTP",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof OTPInput>"
      },
      {
        "name": "InputOTPGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "InputOTPSlot",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & { index: number }",
        "props": [
          {
            "name": "index",
            "type": "number",
            "required": true
          }
        ]
      },
      {
        "name": "InputOTPSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      }
    ]
  },
  "input": {
    "source": "src/ui/input.tsx",
    "exports": [
      {
        "name": "Input",
        "kind": "component",
        "propsType": "React.ComponentProps<\"input\">"
      }
    ]
  },
  "item": {
    "source": "src/ui/item.tsx",
    "exports": [
      {
        "name": "Item",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & VariantProps<typeof itemVariants> & { asChild?: boolean }",
        "props": [
          {
            "name": "variant",
            "type": "null | \"default\" | \"outline\" | \"muted\"",
            "required": false,
            "default": "\"default\""
          },
          {
            "name": "size",
            "type": "null | \"default\" | \"sm\"",
            "required": false,
            "default": "\"default\""
          },
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false"
          }
        ]
      },
      {
        "name": "ItemMedia",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & VariantProps<typeof itemMediaVariants>",
        "props": [
          {
            "name": "variant",
            "type": "null | \"image\" | \"default\" | \"icon\"",
            "required": false,
            "default": "\"default\""
          }
        ]
      },
      {
        "name": "ItemContent",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "ItemActions",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "ItemGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "ItemSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Separator>"
      },
      {
        "name": "ItemTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "ItemDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<\"p\">"
      },
      {
        "name": "ItemHeader",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "ItemFooter",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      }
    ]
  },
  "kbd": {
    "source": "src/ui/kbd.tsx",
    "exports": [
      {
        "name": "Kbd",
        "kind": "component",
        "propsType": "React.ComponentProps<\"kbd\">"
      },
      {
        "name": "KbdGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      }
    ]
  },
  "label": {
    "source": "src/ui/label.tsx",
    "exports": [
      {
        "name": "Label",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof LabelPrimitive.Root>"
      }
    ]
  },
  "menubar": {
    "source": "src/ui/menubar.tsx",
    "exports": [
      {
        "name": "Menubar",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.Root>"
      },
      {
        "name": "MenubarPortal",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.Portal>"
      },
      {
        "name": "MenubarMenu",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.Menu>"
      },
      {
        "name": "MenubarTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.Trigger>"
      },
      {
        "name": "MenubarContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.Content>",
        "props": [
          {
            "name": "align",
            "type": "\"center\" | \"end\" | \"start\"",
            "required": false,
            "default": "\"start\""
          },
          {
            "name": "alignOffset",
            "type": "number",
            "required": false,
            "default": "-4"
          },
          {
            "name": "sideOffset",
            "type": "number",
            "required": false,
            "default": "8"
          }
        ]
      },
      {
        "name": "MenubarGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.Group>"
      },
      {
        "name": "MenubarSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.Separator>"
      },
      {
        "name": "MenubarLabel",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.Label> & { inset?: boolean }",
        "props": [
          {
            "name": "inset",
            "type": "boolean",
            "required": false
          }
        ]
      },
      {
        "name": "MenubarItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.Item> & { inset?: boolean variant?: \"default\" | \"destructive\" }",
        "props": [
          {
            "name": "inset",
            "type": "boolean",
            "required": false
          },
          {
            "name": "variant",
            "type": "\"default\" | \"destructive\"",
            "required": false,
            "default": "\"default\""
          }
        ]
      },
      {
        "name": "MenubarShortcut",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      },
      {
        "name": "MenubarCheckboxItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.CheckboxItem>"
      },
      {
        "name": "MenubarRadioGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.RadioGroup>"
      },
      {
        "name": "MenubarRadioItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.RadioItem>"
      },
      {
        "name": "MenubarSub",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.Sub>"
      },
      {
        "name": "MenubarSubTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.SubTrigger> & { inset?: boolean }",
        "props": [
          {
            "name": "inset",
            "type": "boolean",
            "required": false
          }
        ]
      },
      {
        "name": "MenubarSubContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof MenubarPrimitive.SubContent>"
      }
    ]
  },
  "motion-blur": {
    "source": "src/ui/motion-blur.tsx",
    "exports": [
      {
        "name": "MotionBlurProps",
        "kind": "type",
        "definition": "type MotionBlurProps = Omit<MotionProps, \"preset\">"
      },
      {
        "name": "MotionBlur",
        "kind": "component",
        "description": "Sharpen a mounting element in from an 8px blur. Preconfigured `<Motion preset=\"blur\">`.",
        "propsType": "MotionBlurProps"
      }
    ]
  },
  "motion-fade": {
    "source": "src/ui/motion-fade.tsx",
    "exports": [
      {
        "name": "MotionFadeProps",
        "kind": "type",
        "definition": "type MotionFadeProps = Omit<MotionProps, \"preset\">"
      },
      {
        "name": "MotionFade",
        "kind": "component",
        "description": "Fade a mounting element in. Preconfigured `<Motion preset=\"fade\">`.",
        "propsType": "MotionFadeProps"
      }
    ]
  },
  "motion-scale": {
    "source": "src/ui/motion-scale.tsx",
    "exports": [
      {
        "name": "MotionScaleProps",
        "kind": "type",
        "definition": "type MotionScaleProps = Omit<MotionProps, \"preset\">"
      },
      {
        "name": "MotionScale",
        "kind": "component",
        "description": "Zoom a mounting element in from 95%. Preconfigured `<Motion preset=\"scale\">`.",
        "propsType": "MotionScaleProps"
      }
    ]
  },
  "motion-slide": {
    "source": "src/ui/motion-slide.tsx",
    "exports": [
      {
        "name": "MotionSlideDirection",
        "kind": "type",
        "definition": "type MotionSlideDirection = \"up\" | \"down\" | \"left\" | \"right\""
      },
      {
        "name": "MotionSlideProps",
        "kind": "type",
        "definition": "interface MotionSlideProps extends Omit<MotionProps, \"preset\"> { /** Direction the element travels from as it fades in. Default `\"up\"`. */ direction?: MotionSlideDirection }"
      },
      {
        "name": "MotionSlide",
        "kind": "component",
        "description": "Slide a mounting element in from a direction while it fades.",
        "propsType": "MotionSlideProps",
        "props": [
          {
            "name": "direction",
            "type": "MotionSlideDirection",
            "required": false,
            "default": "\"up\"",
            "description": "Direction the element travels from as it fades in. Default `\"up\"`."
          }
        ]
      }
    ]
  },
  "motion": {
    "source": "src/ui/motion.tsx",
    "exports": [
      {
        "name": "MotionPreset",
        "kind": "type",
        "description": "Motion presets — enter/exit/hover recipes expressed as token-driven class strings on top of `tw-animate-css` (zero runtime deps). The `<Motion>` primitive plays an enter recipe once on mount; the exported maps and helpers let you drop the same recipes onto anything else (a Radix `data-[state]` element, a hand-rolled transition). Timing rides the CSS custom properties tw-animate-css reads: - default duration/easing come from the static `duration-*`/`ease-*` classes baked into `motionEnter`, - the `duration`/`delay` props override them per-instance via `--tw-animation-duration` / `--tw-animation-delay` (no arbitrary Tailwind class is generated at runtime, so it works with any value). Everything degrades under `prefers-reduced-motion`: the enter animation is dropped (content shows immediately) and hover transitions are disabled.",
        "definition": "type MotionPreset = | \"fade\" | \"fade-up\" | \"fade-down\" | \"fade-left\" | \"fade-right\" | \"scale\" | \"blur\""
      },
      {
        "name": "MotionHover",
        "kind": "type",
        "definition": "type MotionHover = \"lift\" | \"sink\" | \"scale\" | \"glow\""
      },
      {
        "name": "motionEnterPresets",
        "kind": "utility",
        "description": "Enter recipes: tw-animate-css `animate-in` sets the keyframe `from` state, the element animates to its natural rendered state."
      },
      {
        "name": "motionExitPresets",
        "kind": "utility",
        "description": "Exit recipes: the mirror of each enter preset, for `animate-out` on a Radix `data-[state=closed]` element."
      },
      {
        "name": "motionHoverPresets",
        "kind": "utility",
        "description": "Hover recipes: plain Tailwind transitions, no keyframes."
      },
      {
        "name": "motionEnter",
        "kind": "utility",
        "description": "Build the class string for an enter recipe (plays on mount).",
        "signature": "(preset: MotionPreset, className?: string): string"
      },
      {
        "name": "motionExit",
        "kind": "utility",
        "description": "Build the class string for an exit recipe (pair with `animate-out`).",
        "signature": "(preset: MotionPreset, className?: string): string"
      },
      {
        "name": "motionHover",
        "kind": "utility",
        "description": "Build the class string for a hover recipe.",
        "signature": "(hover: MotionHover, className?: string): string"
      },
      {
        "name": "MotionProps",
        "kind": "type",
        "definition": "interface MotionProps extends React.ComponentProps<\"div\"> { /** Enter recipe to play on mount. Default `\"fade\"`. */ preset?: MotionPreset /** Optional hover recipe applied to the same element. */ hover?: MotionHover /** Enter duration in milliseconds. Overrides the 500ms default. */ duration?: number /** Enter delay in milliseconds — the knob for staggering a list. */ delay?: number /** Merge props onto the single child instead of rendering a wrapper. */ asChild?: boolean }"
      },
      {
        "name": "Motion",
        "kind": "component",
        "propsType": "MotionProps",
        "props": [
          {
            "name": "preset",
            "type": "MotionPreset",
            "required": false,
            "default": "\"fade\"",
            "description": "Enter recipe to play on mount. Default `\"fade\"`."
          },
          {
            "name": "hover",
            "type": "MotionHover",
            "required": false,
            "description": "Optional hover recipe applied to the same element."
          },
          {
            "name": "duration",
            "type": "number",
            "required": false,
            "description": "Enter duration in milliseconds. Overrides the 500ms default."
          },
          {
            "name": "delay",
            "type": "number",
            "required": false,
            "description": "Enter delay in milliseconds — the knob for staggering a list."
          },
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false",
            "description": "Merge props onto the single child instead of rendering a wrapper."
          }
        ]
      }
    ]
  },
  "native-select": {
    "source": "src/ui/native-select.tsx",
    "exports": [
      {
        "name": "NativeSelect",
        "kind": "component",
        "propsType": "React.ComponentProps<\"select\"> & VariantProps<typeof nativeSelectVariants>",
        "props": [
          {
            "name": "size",
            "type": "undefined",
            "required": false
          }
        ]
      }
    ]
  },
  "navigation-menu": {
    "source": "src/ui/navigation-menu.tsx",
    "exports": [
      {
        "name": "NavigationMenu",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof NavigationMenuPrimitive.Root> & { viewport?: boolean }",
        "props": [
          {
            "name": "viewport",
            "type": "boolean",
            "required": false,
            "default": "true"
          }
        ]
      },
      {
        "name": "NavigationMenuList",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof NavigationMenuPrimitive.List>"
      },
      {
        "name": "NavigationMenuItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof NavigationMenuPrimitive.Item>"
      },
      {
        "name": "NavigationMenuContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof NavigationMenuPrimitive.Content>"
      },
      {
        "name": "NavigationMenuTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof NavigationMenuPrimitive.Trigger>"
      },
      {
        "name": "NavigationMenuLink",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof NavigationMenuPrimitive.Link>"
      },
      {
        "name": "NavigationMenuIndicator",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof NavigationMenuPrimitive.Indicator>"
      },
      {
        "name": "NavigationMenuViewport",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof NavigationMenuPrimitive.Viewport>"
      },
      {
        "name": "navigationMenuTriggerStyle",
        "kind": "utility",
        "signature": "(props?: ClassProp | undefined): string"
      }
    ]
  },
  "number-field": {
    "source": "src/ui/number-field.tsx",
    "exports": [
      {
        "name": "NumberFieldProps",
        "kind": "type",
        "definition": "interface NumberFieldProps extends Omit< React.ComponentProps<\"input\">, \"value\" | \"defaultValue\" | \"onChange\" | \"type\" > { value?: number defaultValue?: number onValueChange?: (value: number) => void min?: number max?: number step?: number }"
      },
      {
        "name": "NumberField",
        "kind": "component",
        "description": "A numeric input with decrement/increment steppers, min/max clamping and step. Controlled via `value`/`onValueChange` or uncontrolled via `defaultValue`. Renders a real `<input type=\"number\">` so native form submission and keyboard work; the native spinners are hidden in favor of the styled buttons.",
        "propsType": "NumberFieldProps",
        "props": [
          {
            "name": "value",
            "type": "number",
            "required": false
          },
          {
            "name": "defaultValue",
            "type": "number",
            "required": false
          },
          {
            "name": "onValueChange",
            "type": "(value: number) => void",
            "required": false
          },
          {
            "name": "min",
            "type": "number",
            "required": false
          },
          {
            "name": "max",
            "type": "number",
            "required": false
          },
          {
            "name": "step",
            "type": "number",
            "required": false,
            "default": "1"
          }
        ]
      }
    ]
  },
  "pagination": {
    "source": "src/ui/pagination.tsx",
    "exports": [
      {
        "name": "Pagination",
        "kind": "component",
        "propsType": "React.ComponentProps<\"nav\">"
      },
      {
        "name": "PaginationContent",
        "kind": "component",
        "propsType": "React.ComponentProps<\"ul\">"
      },
      {
        "name": "PaginationLink",
        "kind": "component",
        "propsType": "PaginationLinkProps",
        "props": [
          {
            "name": "isActive",
            "type": "boolean",
            "required": false
          },
          {
            "name": "size",
            "type": "null | \"default\" | \"sm\" | \"lg\" | \"icon\"",
            "required": false,
            "default": "\"icon\""
          }
        ]
      },
      {
        "name": "PaginationItem",
        "kind": "component",
        "propsType": "React.ComponentProps<\"li\">"
      },
      {
        "name": "PaginationPrevious",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof PaginationLink>"
      },
      {
        "name": "PaginationNext",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof PaginationLink>"
      },
      {
        "name": "PaginationEllipsis",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      }
    ]
  },
  "parallax": {
    "source": "src/ui/parallax.tsx",
    "exports": [
      {
        "name": "ParallaxProps",
        "kind": "type",
        "definition": "interface ParallaxProps extends React.ComponentProps<\"div\"> { /** How far the layer drifts, any CSS length/percentage. Default `\"12%\"`. */ range?: string }"
      },
      {
        "name": "Parallax",
        "kind": "component",
        "propsType": "ParallaxProps",
        "props": [
          {
            "name": "range",
            "type": "string",
            "required": false,
            "default": "\"12%\"",
            "description": "How far the layer drifts, any CSS length/percentage. Default `\"12%\"`."
          }
        ]
      }
    ]
  },
  "popover": {
    "source": "src/ui/popover.tsx",
    "exports": [
      {
        "name": "Popover",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof PopoverPrimitive.Root>"
      },
      {
        "name": "PopoverTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof PopoverPrimitive.Trigger>"
      },
      {
        "name": "PopoverContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof PopoverPrimitive.Content>",
        "props": [
          {
            "name": "align",
            "type": "\"center\" | \"end\" | \"start\"",
            "required": false,
            "default": "\"center\""
          },
          {
            "name": "sideOffset",
            "type": "number",
            "required": false,
            "default": "4"
          }
        ]
      },
      {
        "name": "PopoverAnchor",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof PopoverPrimitive.Anchor>"
      }
    ]
  },
  "progress": {
    "source": "src/ui/progress.tsx",
    "exports": [
      {
        "name": "Progress",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ProgressPrimitive.Root>",
        "props": [
          {
            "name": "aria-label",
            "type": "string",
            "required": false,
            "default": "\"Progress\""
          }
        ]
      }
    ]
  },
  "radio-group": {
    "source": "src/ui/radio-group.tsx",
    "exports": [
      {
        "name": "RadioGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof RadioGroupPrimitive.Root>"
      },
      {
        "name": "RadioGroupItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof RadioGroupPrimitive.Item>"
      }
    ]
  },
  "rating": {
    "source": "src/ui/rating.tsx",
    "exports": [
      {
        "name": "Rating",
        "kind": "component",
        "description": "Rating — a star (or custom icon) rating following the radio-group pattern: each star is a radio, arrows move the value, hover previews it. `readOnly` renders a static, labelled image instead.",
        "propsType": "Omit<React.ComponentProps<\"div\">, \"defaultValue\" | \"onChange\"> & { value?: number defaultValue?: number onValueChange?: (value: number) => void max?: number readOnly?: boolean disabled?: boolean icon?: React.ReactNode }",
        "props": [
          {
            "name": "value",
            "type": "number",
            "required": false
          },
          {
            "name": "defaultValue",
            "type": "number",
            "required": false
          },
          {
            "name": "onValueChange",
            "type": "(value: number) => void",
            "required": false
          },
          {
            "name": "max",
            "type": "number",
            "required": false,
            "default": "5"
          },
          {
            "name": "readOnly",
            "type": "boolean",
            "required": false,
            "default": "false"
          },
          {
            "name": "disabled",
            "type": "boolean",
            "required": false,
            "default": "false"
          },
          {
            "name": "icon",
            "type": "React.ReactNode",
            "required": false
          },
          {
            "name": "aria-label",
            "type": "string",
            "required": false,
            "default": "\"Rating\""
          }
        ]
      }
    ]
  },
  "resizable": {
    "source": "src/ui/resizable.tsx",
    "exports": [
      {
        "name": "ResizablePanelGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ResizablePanelGroupPrimitive> & { direction?: \"horizontal\" | \"vertical\" }",
        "props": [
          {
            "name": "direction",
            "type": "\"horizontal\" | \"vertical\"",
            "required": false,
            "default": "\"horizontal\""
          }
        ]
      },
      {
        "name": "ResizablePanel",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ResizablePanelPrimitive>"
      },
      {
        "name": "ResizableHandle",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ResizableSeparatorPrimitive> & { withHandle?: boolean }",
        "props": [
          {
            "name": "withHandle",
            "type": "boolean",
            "required": false
          }
        ]
      }
    ]
  },
  "scroll-area": {
    "source": "src/ui/scroll-area.tsx",
    "exports": [
      {
        "name": "ScrollArea",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ScrollAreaPrimitive.Root>"
      },
      {
        "name": "ScrollBar",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>",
        "props": [
          {
            "name": "orientation",
            "type": "\"horizontal\" | \"vertical\"",
            "required": false,
            "default": "\"vertical\""
          }
        ]
      }
    ]
  },
  "scroll-reveal": {
    "source": "src/ui/scroll-reveal.tsx",
    "exports": [
      {
        "name": "ScrollRevealProps",
        "kind": "type",
        "description": "Plays a motion enter recipe when the element scrolls into view (rather than on mount like `<Motion>`). Built on the `useInView` IntersectionObserver hook and the motion engine's recipes, so it shares the same presets, timing and prefers-reduced-motion fallback. SSR- and no-JS-safe: it renders visible until it has mounted and armed, so search engines and scriptless clients always see the content.",
        "definition": "interface ScrollRevealProps extends React.ComponentProps<\"div\">, Pick<UseInViewOptions, \"once\" | \"amount\" | \"margin\" | \"root\"> { /** Enter recipe to play when revealed. Default `\"fade-up\"`. */ preset?: MotionPreset /** Reveal duration in milliseconds. Overrides the 500ms default. */ duration?: number /** Reveal delay in milliseconds — the knob for staggering a group. */ delay?: number /** Merge props onto the single child instead of rendering a wrapper. */ asChild?: boolean }"
      },
      {
        "name": "ScrollReveal",
        "kind": "component",
        "propsType": "ScrollRevealProps",
        "props": [
          {
            "name": "preset",
            "type": "MotionPreset",
            "required": false,
            "default": "\"fade-up\"",
            "description": "Enter recipe to play when revealed. Default `\"fade-up\"`."
          },
          {
            "name": "duration",
            "type": "number",
            "required": false,
            "description": "Reveal duration in milliseconds. Overrides the 500ms default."
          },
          {
            "name": "delay",
            "type": "number",
            "required": false,
            "description": "Reveal delay in milliseconds — the knob for staggering a group."
          },
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false",
            "description": "Merge props onto the single child instead of rendering a wrapper."
          },
          {
            "name": "once",
            "type": "boolean",
            "required": false,
            "default": "true",
            "description": "Stop observing after the first time the element enters view. Default `true`."
          },
          {
            "name": "amount",
            "type": "number",
            "required": false,
            "default": "0.3",
            "description": "Fraction of the element that must be visible to count as in view (0–1). Default `0.3`."
          },
          {
            "name": "margin",
            "type": "string",
            "required": false,
            "default": "\"0px\"",
            "description": "IntersectionObserver `rootMargin`, e.g. `\"-10% 0px\"`. Default `\"0px\"`."
          }
        ]
      }
    ]
  },
  "select": {
    "source": "src/ui/select.tsx",
    "exports": [
      {
        "name": "Select",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SelectPrimitive.Root>"
      },
      {
        "name": "SelectContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SelectPrimitive.Content>",
        "props": [
          {
            "name": "position",
            "type": "\"item-aligned\" | \"popper\"",
            "required": false,
            "default": "\"popper\""
          }
        ]
      },
      {
        "name": "SelectGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SelectPrimitive.Group>"
      },
      {
        "name": "SelectItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SelectPrimitive.Item>"
      },
      {
        "name": "SelectLabel",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SelectPrimitive.Label>"
      },
      {
        "name": "SelectScrollDownButton",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SelectPrimitive.ScrollDownButton>"
      },
      {
        "name": "SelectScrollUpButton",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SelectPrimitive.ScrollUpButton>"
      },
      {
        "name": "SelectSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SelectPrimitive.Separator>"
      },
      {
        "name": "SelectTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SelectPrimitive.Trigger> & { size?: \"sm\" | \"default\" }",
        "props": [
          {
            "name": "size",
            "type": "\"sm\" | \"default\"",
            "required": false,
            "default": "\"default\""
          }
        ]
      },
      {
        "name": "SelectValue",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SelectPrimitive.Value>"
      }
    ]
  },
  "separator": {
    "source": "src/ui/separator.tsx",
    "exports": [
      {
        "name": "Separator",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SeparatorPrimitive.Root>",
        "props": [
          {
            "name": "orientation",
            "type": "\"horizontal\" | \"vertical\"",
            "required": false,
            "default": "\"horizontal\"",
            "description": "Either `vertical` or `horizontal`. Defaults to `horizontal`."
          },
          {
            "name": "decorative",
            "type": "boolean",
            "required": false,
            "default": "true",
            "description": "Whether or not the component is purely decorative. When true, accessibility-related attributes are updated so that that the rendered element is removed from the accessibility tree."
          }
        ]
      }
    ]
  },
  "sheet": {
    "source": "src/ui/sheet.tsx",
    "exports": [
      {
        "name": "Sheet",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SheetPrimitive.Root>"
      },
      {
        "name": "SheetTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SheetPrimitive.Trigger>"
      },
      {
        "name": "SheetClose",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SheetPrimitive.Close>"
      },
      {
        "name": "SheetContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SheetPrimitive.Content> & VariantProps<typeof sheetVariants>",
        "props": [
          {
            "name": "side",
            "type": "null | \"top\" | \"bottom\" | \"left\" | \"right\"",
            "required": false,
            "default": "\"right\""
          }
        ]
      },
      {
        "name": "SheetHeader",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "SheetFooter",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "SheetTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SheetPrimitive.Title>"
      },
      {
        "name": "SheetDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SheetPrimitive.Description>"
      }
    ]
  },
  "sidebar": {
    "source": "src/ui/sidebar.tsx",
    "exports": [
      {
        "name": "Sidebar",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & { side?: \"left\" | \"right\" variant?: \"sidebar\" | \"floating\" | \"inset\" collapsible?: \"offcanvas\" | \"icon\" | \"none\" }",
        "props": [
          {
            "name": "side",
            "type": "\"left\" | \"right\"",
            "required": false,
            "default": "\"left\""
          },
          {
            "name": "variant",
            "type": "\"sidebar\" | \"floating\" | \"inset\"",
            "required": false,
            "default": "\"sidebar\""
          },
          {
            "name": "collapsible",
            "type": "\"offcanvas\" | \"icon\" | \"none\"",
            "required": false,
            "default": "\"offcanvas\""
          }
        ]
      },
      {
        "name": "SidebarContent",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "SidebarFooter",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "SidebarGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "SidebarGroupAction",
        "kind": "component",
        "propsType": "React.ComponentProps<\"button\"> & { asChild?: boolean }",
        "props": [
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false"
          }
        ]
      },
      {
        "name": "SidebarGroupContent",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "SidebarGroupLabel",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & { asChild?: boolean }",
        "props": [
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false"
          }
        ]
      },
      {
        "name": "SidebarHeader",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "SidebarInput",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Input>"
      },
      {
        "name": "SidebarInset",
        "kind": "component",
        "propsType": "React.ComponentProps<\"main\">"
      },
      {
        "name": "SidebarMenu",
        "kind": "component",
        "propsType": "React.ComponentProps<\"ul\">"
      },
      {
        "name": "SidebarMenuAction",
        "kind": "component",
        "propsType": "React.ComponentProps<\"button\"> & { asChild?: boolean showOnHover?: boolean }",
        "props": [
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false"
          },
          {
            "name": "showOnHover",
            "type": "boolean",
            "required": false,
            "default": "false"
          }
        ]
      },
      {
        "name": "SidebarMenuBadge",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "SidebarMenuButton",
        "kind": "component",
        "propsType": "React.ComponentProps<\"button\"> & { asChild?: boolean isActive?: boolean tooltip?: string | React.ComponentProps<typeof TooltipContent> } & VariantProps<typeof sidebarMenuButtonVariants>",
        "props": [
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false"
          },
          {
            "name": "isActive",
            "type": "boolean",
            "required": false,
            "default": "false"
          },
          {
            "name": "variant",
            "type": "null | \"default\" | \"outline\"",
            "required": false,
            "default": "\"default\""
          },
          {
            "name": "size",
            "type": "null | \"default\" | \"sm\" | \"lg\"",
            "required": false,
            "default": "\"default\""
          },
          {
            "name": "tooltip",
            "type": "string | React.ComponentProps<typeof TooltipContent>",
            "required": false
          }
        ]
      },
      {
        "name": "SidebarMenuItem",
        "kind": "component",
        "propsType": "React.ComponentProps<\"li\">"
      },
      {
        "name": "SidebarMenuSkeleton",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & { showIcon?: boolean }",
        "props": [
          {
            "name": "showIcon",
            "type": "boolean",
            "required": false,
            "default": "false"
          }
        ]
      },
      {
        "name": "SidebarMenuSub",
        "kind": "component",
        "propsType": "React.ComponentProps<\"ul\">"
      },
      {
        "name": "SidebarMenuSubButton",
        "kind": "component",
        "propsType": "React.ComponentProps<\"a\"> & { asChild?: boolean size?: \"sm\" | \"md\" isActive?: boolean }",
        "props": [
          {
            "name": "asChild",
            "type": "boolean",
            "required": false,
            "default": "false"
          },
          {
            "name": "size",
            "type": "\"sm\" | \"md\"",
            "required": false,
            "default": "\"md\""
          },
          {
            "name": "isActive",
            "type": "boolean",
            "required": false,
            "default": "false"
          }
        ]
      },
      {
        "name": "SidebarMenuSubItem",
        "kind": "component",
        "propsType": "React.ComponentProps<\"li\">"
      },
      {
        "name": "SidebarProvider",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\"> & { defaultOpen?: boolean open?: boolean onOpenChange?: (open: boolean) => void }",
        "props": [
          {
            "name": "defaultOpen",
            "type": "boolean",
            "required": false,
            "default": "true"
          },
          {
            "name": "open",
            "type": "boolean",
            "required": false
          },
          {
            "name": "onOpenChange",
            "type": "(open: boolean) => void",
            "required": false
          }
        ]
      },
      {
        "name": "SidebarRail",
        "kind": "component",
        "propsType": "React.ComponentProps<\"button\">"
      },
      {
        "name": "SidebarSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Separator>"
      },
      {
        "name": "SidebarTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof Button>"
      },
      {
        "name": "useSidebar",
        "kind": "hook",
        "signature": "(): SidebarContextProps"
      }
    ]
  },
  "skeleton": {
    "source": "src/ui/skeleton.tsx",
    "exports": [
      {
        "name": "Skeleton",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      }
    ]
  },
  "slider": {
    "source": "src/ui/slider.tsx",
    "exports": [
      {
        "name": "Slider",
        "kind": "component",
        "propsType": "SliderProps",
        "props": [
          {
            "name": "min",
            "type": "number",
            "required": false,
            "default": "0"
          },
          {
            "name": "max",
            "type": "number",
            "required": false,
            "default": "100"
          },
          {
            "name": "thumbLabels",
            "type": "string[]",
            "required": false
          },
          {
            "name": "aria-label",
            "type": "string",
            "required": false,
            "default": "\"Slider value\""
          }
        ]
      }
    ]
  },
  "sonner": {
    "source": "src/ui/sonner.tsx",
    "exports": [
      {
        "name": "Toaster",
        "kind": "component",
        "propsType": "ToasterProps",
        "props": [
          {
            "name": "theme",
            "type": "\"light\" | \"dark\" | \"system\"",
            "required": false,
            "default": "\"system\""
          }
        ]
      }
    ]
  },
  "spinner": {
    "source": "src/ui/spinner.tsx",
    "exports": [
      {
        "name": "Spinner",
        "kind": "component",
        "propsType": "React.ComponentProps<\"svg\">"
      }
    ]
  },
  "stepper": {
    "source": "src/ui/stepper.tsx",
    "exports": [
      {
        "name": "Stepper",
        "kind": "component",
        "propsType": "Omit<React.ComponentProps<\"ol\">, \"defaultValue\"> & { value?: number defaultValue?: number onValueChange?: (step: number) => void orientation?: \"horizontal\" | \"vertical\" }",
        "props": [
          {
            "name": "value",
            "type": "number",
            "required": false
          },
          {
            "name": "defaultValue",
            "type": "number",
            "required": false
          },
          {
            "name": "onValueChange",
            "type": "(step: number) => void",
            "required": false
          },
          {
            "name": "orientation",
            "type": "\"horizontal\" | \"vertical\"",
            "required": false,
            "default": "\"horizontal\""
          }
        ]
      },
      {
        "name": "StepperItem",
        "kind": "component",
        "propsType": "React.ComponentProps<\"li\"> & { step: number disabled?: boolean }",
        "props": [
          {
            "name": "step",
            "type": "number",
            "required": true
          },
          {
            "name": "disabled",
            "type": "boolean",
            "required": false,
            "default": "false"
          }
        ]
      },
      {
        "name": "StepperTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<\"button\">"
      },
      {
        "name": "StepperIndicator",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      },
      {
        "name": "StepperTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      },
      {
        "name": "StepperDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      },
      {
        "name": "StepperSeparator",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      }
    ]
  },
  "switch": {
    "source": "src/ui/switch.tsx",
    "exports": [
      {
        "name": "Switch",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof SwitchPrimitive.Root>"
      }
    ]
  },
  "table": {
    "source": "src/ui/table.tsx",
    "exports": [
      {
        "name": "Table",
        "kind": "component",
        "propsType": "React.ComponentProps<\"table\">"
      },
      {
        "name": "TableHeader",
        "kind": "component",
        "propsType": "React.ComponentProps<\"thead\">"
      },
      {
        "name": "TableBody",
        "kind": "component",
        "propsType": "React.ComponentProps<\"tbody\">"
      },
      {
        "name": "TableFooter",
        "kind": "component",
        "propsType": "React.ComponentProps<\"tfoot\">"
      },
      {
        "name": "TableHead",
        "kind": "component",
        "propsType": "React.ComponentProps<\"th\">"
      },
      {
        "name": "TableRow",
        "kind": "component",
        "propsType": "React.ComponentProps<\"tr\">"
      },
      {
        "name": "TableCell",
        "kind": "component",
        "propsType": "React.ComponentProps<\"td\">"
      },
      {
        "name": "TableCaption",
        "kind": "component",
        "propsType": "React.ComponentProps<\"caption\">"
      }
    ]
  },
  "tabs": {
    "source": "src/ui/tabs.tsx",
    "exports": [
      {
        "name": "Tabs",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof TabsPrimitive.Root>"
      },
      {
        "name": "TabsList",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof TabsPrimitive.List>"
      },
      {
        "name": "TabsTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof TabsPrimitive.Trigger>"
      },
      {
        "name": "TabsContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof TabsPrimitive.Content>"
      }
    ]
  },
  "tags-input": {
    "source": "src/ui/tags-input.tsx",
    "exports": [
      {
        "name": "TagsInput",
        "kind": "component",
        "description": "Tags input — free-form multi-value entry rendered as removable chips. Enter or comma commits the draft, paste splits on commas, Backspace on an empty draft removes the last tag. Duplicates are ignored; `max` caps the list.",
        "propsType": "Omit<React.ComponentProps<\"div\">, \"defaultValue\" | \"onChange\"> & { value?: string[] defaultValue?: string[] onValueChange?: (value: string[]) => void placeholder?: string max?: number disabled?: boolean }",
        "props": [
          {
            "name": "value",
            "type": "string[]",
            "required": false
          },
          {
            "name": "defaultValue",
            "type": "string[]",
            "required": false
          },
          {
            "name": "onValueChange",
            "type": "(value: string[]) => void",
            "required": false
          },
          {
            "name": "placeholder",
            "type": "string",
            "required": false
          },
          {
            "name": "max",
            "type": "number",
            "required": false
          },
          {
            "name": "disabled",
            "type": "boolean",
            "required": false
          }
        ]
      }
    ]
  },
  "textarea": {
    "source": "src/ui/textarea.tsx",
    "exports": [
      {
        "name": "Textarea",
        "kind": "component",
        "propsType": "React.ComponentProps<\"textarea\">"
      }
    ]
  },
  "timeline": {
    "source": "src/ui/timeline.tsx",
    "exports": [
      {
        "name": "Timeline",
        "kind": "component",
        "description": "A vertical timeline for activity feeds, changelogs and process histories. Composable: each `TimelineItem` holds a `TimelineIndicator` (the dot + the connector line to the next item) and a `TimelineContent`. The connector is hidden on the last item automatically.",
        "propsType": "React.ComponentProps<\"ol\">"
      },
      {
        "name": "TimelineItem",
        "kind": "component",
        "propsType": "React.ComponentProps<\"li\">"
      },
      {
        "name": "TimelineIndicator",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "TimelineContent",
        "kind": "component",
        "propsType": "React.ComponentProps<\"div\">"
      },
      {
        "name": "TimelineTime",
        "kind": "component",
        "propsType": "React.ComponentProps<\"span\">"
      },
      {
        "name": "TimelineTitle",
        "kind": "component",
        "propsType": "React.ComponentProps<\"h3\">"
      },
      {
        "name": "TimelineDescription",
        "kind": "component",
        "propsType": "React.ComponentProps<\"p\">"
      }
    ]
  },
  "toggle-group": {
    "source": "src/ui/toggle-group.tsx",
    "exports": [
      {
        "name": "ToggleGroup",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ToggleGroupPrimitive.Root> & VariantProps<typeof toggleVariants>",
        "props": [
          {
            "name": "variant",
            "type": "null | \"default\" | \"outline\"",
            "required": false
          },
          {
            "name": "size",
            "type": "null | \"default\" | \"sm\" | \"lg\"",
            "required": false
          }
        ]
      },
      {
        "name": "ToggleGroupItem",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof ToggleGroupPrimitive.Item> & VariantProps<typeof toggleVariants>",
        "props": [
          {
            "name": "variant",
            "type": "null | \"default\" | \"outline\"",
            "required": false
          },
          {
            "name": "size",
            "type": "null | \"default\" | \"sm\" | \"lg\"",
            "required": false
          }
        ]
      }
    ]
  },
  "toggle": {
    "source": "src/ui/toggle.tsx",
    "exports": [
      {
        "name": "Toggle",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof TogglePrimitive.Root> & VariantProps<typeof toggleVariants>",
        "props": [
          {
            "name": "variant",
            "type": "null | \"default\" | \"outline\"",
            "required": false
          },
          {
            "name": "size",
            "type": "null | \"default\" | \"sm\" | \"lg\"",
            "required": false
          }
        ]
      },
      {
        "name": "toggleVariants",
        "kind": "utility",
        "signature": "(props?: (ConfigVariants<{ variant: { default: string; outline: string; }; size: { default: string; sm: string; lg: string; }; }> & ClassProp) | undefined): string"
      }
    ]
  },
  "tooltip": {
    "source": "src/ui/tooltip.tsx",
    "exports": [
      {
        "name": "Tooltip",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof TooltipPrimitive.Root>"
      },
      {
        "name": "TooltipTrigger",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof TooltipPrimitive.Trigger>"
      },
      {
        "name": "TooltipContent",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof TooltipPrimitive.Content>",
        "props": [
          {
            "name": "sideOffset",
            "type": "number",
            "required": false,
            "default": "0"
          }
        ]
      },
      {
        "name": "TooltipProvider",
        "kind": "component",
        "propsType": "React.ComponentProps<typeof TooltipPrimitive.Provider>",
        "props": [
          {
            "name": "delayDuration",
            "type": "number",
            "required": false,
            "default": "0",
            "description": "The duration from when the pointer enters the trigger until the tooltip gets opened."
          }
        ]
      }
    ]
  },
  "tree-view": {
    "source": "src/ui/tree-view.tsx",
    "exports": [
      {
        "name": "TreeView",
        "kind": "component",
        "propsType": "Omit<React.ComponentProps<\"ul\">, \"onSelect\"> & { expanded?: string[] defaultExpanded?: string[] onExpandedChange?: (expanded: string[]) => void selected?: string | null defaultSelected?: string | null onSelectedChange?: (selected: string | null) => void }",
        "props": [
          {
            "name": "expanded",
            "type": "string[]",
            "required": false
          },
          {
            "name": "defaultExpanded",
            "type": "string[]",
            "required": false
          },
          {
            "name": "onExpandedChange",
            "type": "(expanded: string[]) => void",
            "required": false
          },
          {
            "name": "selected",
            "type": "string | null",
            "required": false
          },
          {
            "name": "defaultSelected",
            "type": "string | null",
            "required": false
          },
          {
            "name": "onSelectedChange",
            "type": "(selected: string | null) => void",
            "required": false
          }
        ]
      },
      {
        "name": "TreeItem",
        "kind": "component",
        "propsType": "Omit<React.ComponentProps<\"li\">, \"onSelect\"> & { value: string label: React.ReactNode icon?: React.ReactNode disabled?: boolean }",
        "props": [
          {
            "name": "value",
            "type": "string",
            "required": true
          },
          {
            "name": "label",
            "type": "React.ReactNode",
            "required": true
          },
          {
            "name": "icon",
            "type": "React.ReactNode",
            "required": false
          },
          {
            "name": "disabled",
            "type": "boolean",
            "required": false
          }
        ]
      }
    ]
  }
}
