/**
 * Theme data + serialization for the /create configurator.
 *
 * The data itself — base scales, accents, chart ramps, radii, fonts, the
 * preset codec and the CSS emitters — lives in @logic2b/tokens, the single
 * source of truth shared with the CLI preset engine and the MCP theme tools.
 * This module re-exports it, re-exports the shared DESIGN.md generator,
 * and adds the web-only typeset.css and components.json exports.
 */

import { buildTypesetCss, type ThemeConfig } from "@logic2b/tokens"

export {
  ACCENTS,
  BASE_COLORS,
  CHARTS,
  CUSTOM_KEY_RE,
  DEFAULT_CONFIG,
  FLOWS,
  FONTS,
  ICON_LIBRARIES,
  LEADINGS,
  MEASURES,
  RADII,
  SIZES,
  applyPresetToCss,
  auditTypeset,
  buildCss,
  buildTypesetCss,
  customAccent,
  customChart,
  customKey,
  decodePreset,
  encodePreset,
  parseCustomKey,
  presetDeclarations,
  resolveTokens,
  resolveTypeset,
  sidebarTokens,
  typesetDeclarations,
  type AccentColor,
  type BaseColor,
  type ChartPalette,
  type ChartRamp,
  type Mode,
  type ReadabilityCheck,
  type ResolvedTypeset,
  type ThemeConfig,
  type IconLibrary,
  type TokenSet,
} from "@logic2b/tokens"

export { buildDesignMd } from "@logic2b/scaffold/rules"

/** The FONTS keys that ship a real fontsource package in this repo (see the
 *  `@import` lines in apps/web/src/styles/global.css). Every other FONTS
 *  entry is a system font stack — nothing to install. */
const FONTSOURCE_PACKAGES: Record<string, string> = {
  inter: "@fontsource-variable/inter",
  grotesk: "@fontsource-variable/space-grotesk",
}

/** Unique fontsource imports needed for a config's heading/body/mono picks,
 *  in a stable order (heading, body, mono). */
export function fontsourceImportsFor(cfg: ThemeConfig): string[] {
  const seen = new Set<string>()
  for (const key of [cfg.heading, cfg.font, cfg.mono]) {
    const pkg = FONTSOURCE_PACKAGES[key]
    if (pkg) seen.add(pkg)
  }
  return [...seen]
}

/** typeset.css — the /typeset studio's export: font-family + rhythm tokens,
 *  the fontsource imports the config actually needs, and a `.prose` recipe
 *  that applies the scale (measure/size/leading/flow) to prose content. */
export function buildTypesetCssExport(cfg: ThemeConfig, presetId: string): string {
  const imports = fontsourceImportsFor(cfg)
  const importLines = imports.map((pkg) => `@import "${pkg}";`).join("\n")
  const tokens = buildTypesetCss(cfg)
  return `/* typeset.css — generated by logic2b ui (/typeset) · preset ${presetId}
   Drop this file next to your main stylesheet and import it after your
   theme CSS: @import "./typeset.css"; */
${imports.length > 0 ? `\n${importLines}\n` : ""}
${tokens}

/* Apply the scale to prose content (a docs article, a blog post, …): */
.prose {
  max-width: var(--type-measure);
  font-size: var(--type-size-base);
  line-height: var(--type-leading-base);
}
.prose > * + * {
  margin-top: var(--type-flow);
}
.prose :is(h1, h2, h3, h4) {
  font-family: var(--font-heading);
}
.prose :is(code, pre) {
  font-family: var(--font-mono);
}
`
}

/** components.json the CLI understands. */
export function buildComponentsJson(cfg: ThemeConfig): string {
  return JSON.stringify(
    {
      $schema: "https://ui.logic2b.com/schema.json",
      style: "default",
      tailwind: { config: "", css: "src/styles/global.css", baseColor: cfg.base, cssVariables: true },
      aliases: { components: "@/components", ui: "@/components/ui", lib: "@/lib", hooks: "@/hooks" },
      iconLibrary: cfg.iconLibrary,
    },
    null,
    2,
  )
}
